<?php

/**
 * GEOSERVER API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class DeviceAttachmentApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation createDeviceAttachment
     *
     * Create Device Attachment.
     *
     *
     * @return Http response
     */
    public function createDeviceAttachment()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling createDeviceAttachment');
        }
        $body = $input['body'];


        return response('How about implementing createDeviceAttachment as a post method ?');
    }
    /**
     * Operation listDeviceAttachment
     *
     * List of device attachment.
     *
     *
     * @return Http response
     */
    public function listDeviceAttachment()
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing listDeviceAttachment as a get method ?');
    }
    /**
     * Operation getDeviceAttachmentByProductId
     *
     * Find Device Attachment by company ID.
     *
     * @param int $product_id ID of company to return (required)
     *
     * @return Http response
     */
    public function getDeviceAttachmentByProductId($product_id)
    {
        $input = Request::all();

        //path params validation
        if ($product_id < 1) {
            throw new \InvalidArgumentException('invalid value for $product_id when calling DeviceAttachmentApi.getDeviceAttachmentByProductId, must be bigger than or equal to 1.');
        }


        //not path params validation

        return response('How about implementing getDeviceAttachmentByProductId as a get method ?');
    }
    /**
     * Operation deleteDeviceAttachment
     *
     * Delete a Device Attachment.
     *
     * @param int $device_attachment_id device attachment Id to delete (required)
     *
     * @return Http response
     */
    public function deleteDeviceAttachment($device_attachment_id)
    {
        $input = Request::all();

        //path params validation
        if ($device_attachment_id < 1) {
            throw new \InvalidArgumentException('invalid value for $device_attachment_id when calling DeviceAttachmentApi.deleteDeviceAttachment, must be bigger than or equal to 1.');
        }


        //not path params validation

        return response('How about implementing deleteDeviceAttachment as a delete method ?');
    }
}
