<?php

/**
 * GEOSERVER API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class DevicesApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation createDevice
     *
     * Create Device.
     *
     *
     * @return Http response
     */
    public function createDevice()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling createDevice');
        }
        $body = $input['body'];


        return response('How about implementing createDevice as a post method ?');
    }
    /**
     * Operation listDevices
     *
     * List of Devices.
     *
     *
     * @return Http response
     */
    public function listDevices()
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing listDevices as a get method ?');
    }
    /**
     * Operation updateDevice
     *
     * Updates a device.
     *
     *
     * @return Http response
     */
    public function updateDevice()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $body = $input['body'];


        return response('How about implementing updateDevice as a patch method ?');
    }
    /**
     * Operation deleteDevice
     *
     * Delete a Device.
     *
     * @param int $device_id device Id to delete (required)
     *
     * @return Http response
     */
    public function deleteDevice($device_id)
    {
        $input = Request::all();

        //path params validation
        if ($device_id < 1) {
            throw new \InvalidArgumentException('invalid value for $device_id when calling DevicesApi.deleteDevice, must be bigger than or equal to 1.');
        }


        //not path params validation

        return response('How about implementing deleteDevice as a delete method ?');
    }
    /**
     * Operation getDeviceById
     *
     * Find Device by ID.
     *
     * @param int $device_id ID of device to return (required)
     *
     * @return Http response
     */
    public function getDeviceById($device_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getDeviceById as a get method ?');
    }
}
