<?php

/**
 * GEOSERVER API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class ProductsApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation createProduct
     *
     * Create Product.
     *
     *
     * @return Http response
     */
    public function createProduct()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $body = $input['body'];


        return response('How about implementing createProduct as a post method ?');
    }
    /**
     * Operation listProducts
     *
     * List of Products.
     *
     *
     * @return Http response
     */
    public function listProducts()
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing listProducts as a get method ?');
    }
    /**
     * Operation updateProduct
     *
     * Updates a Product.
     *
     *
     * @return Http response
     */
    public function updateProduct()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $body = $input['body'];


        return response('How about implementing updateProduct as a patch method ?');
    }
    /**
     * Operation listProductsByCompanyId
     *
     * List of products by company id.
     *
     * @param int $company_id ID of company to return (required)
     *
     * @return Http response
     */
    public function listProductsByCompanyId($company_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing listProductsByCompanyId as a get method ?');
    }
    /**
     * Operation deleteProduct
     *
     * Delete a Product.
     *
     * @param int $product_id product Id to delete (required)
     *
     * @return Http response
     */
    public function deleteProduct($product_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteProduct as a delete method ?');
    }
    /**
     * Operation getProductById
     *
     * Find Product by ID.
     *
     * @param int $product_id ID of Product to return (required)
     *
     * @return Http response
     */
    public function getProductById($product_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getProductById as a get method ?');
    }
}
