<?php

/**
 * GEOSERVER API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class StatusApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation createStatus
     *
     * Create Status.
     *
     *
     * @return Http response
     */
    public function createStatus()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $body = $input['body'];


        return response('How about implementing createStatus as a post method ?');
    }
    /**
     * Operation listStatus
     *
     * List of Status.
     *
     *
     * @return Http response
     */
    public function listStatus()
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing listStatus as a get method ?');
    }
    /**
     * Operation updateStatus
     *
     * Updates a status.
     *
     *
     * @return Http response
     */
    public function updateStatus()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $body = $input['body'];


        return response('How about implementing updateStatus as a patch method ?');
    }
    /**
     * Operation deleteStatus
     *
     * Delete a Status.
     *
     * @param int $status_id Status Id to delete (required)
     *
     * @return Http response
     */
    public function deleteStatus($status_id)
    {
        $input = Request::all();

        //path params validation
        if ($status_id < 1) {
            throw new \InvalidArgumentException('invalid value for $status_id when calling StatusApi.deleteStatus, must be bigger than or equal to 1.');
        }


        //not path params validation

        return response('How about implementing deleteStatus as a delete method ?');
    }
    /**
     * Operation getStatusById
     *
     * Find status by ID.
     *
     * @param int $status_id ID of Status to return (required)
     *
     * @return Http response
     */
    public function getStatusById($status_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getStatusById as a get method ?');
    }
}
