/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ModelPing.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace api {

ModelPing::ModelPing(QString* json) {
    init();
    this->fromJson(*json);
}

ModelPing::ModelPing() {
    init();
}

ModelPing::~ModelPing() {
    this->cleanup();
}

void
ModelPing::init() {
    ip = new QString("");
}

void
ModelPing::cleanup() {
    if(ip != nullptr) {
        delete ip;
    }
}

ModelPing*
ModelPing::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ModelPing::fromJsonObject(QJsonObject &pJson) {
    ::api::setValue(&ip, pJson["ip"], "QString", "QString");
}

QString
ModelPing::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
ModelPing::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    toJsonValue(QString("ip"), ip, obj, QString("QString"));

    return obj;
}

QString*
ModelPing::getIp() {
    return ip;
}
void
ModelPing::setIp(QString* ip) {
    this->ip = ip;
}


}

