/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ModelRpStaffForm.h
 * 
 * 
 */

#ifndef ModelRpStaffForm_H_
#define ModelRpStaffForm_H_

#include <QJsonObject>


#include <QDateTime>
#include <QString>

#include "SWGObject.h"

namespace api {

class ModelRpStaffForm: public SWGObject {
public:
    ModelRpStaffForm();
    ModelRpStaffForm(QString* json);
    virtual ~ModelRpStaffForm();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    ModelRpStaffForm* fromJson(QString &jsonString);

    QDateTime* getFromDate();
    void setFromDate(QDateTime* from_date);

    QDateTime* getToDate();
    void setToDate(QDateTime* to_date);

    qint64 getRouteId();
    void setRouteId(qint64 route_id);

    QString* getPosition();
    void setPosition(QString* position);


private:
    QDateTime* from_date;
    QDateTime* to_date;
    qint64 route_id;
    QString* position;
};

}

#endif /* ModelRpStaffForm_H_ */
