/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ModelRoute.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace api {

ModelRoute::ModelRoute(QString* json) {
    init();
    this->fromJson(*json);
}

ModelRoute::ModelRoute() {
    init();
}

ModelRoute::~ModelRoute() {
    this->cleanup();
}

void
ModelRoute::init() {
    id = 0L;
    comany_id = 0L;
    start_time = new QString("");
    end_time = new QString("");
    number = new QString("");
    name = new QString("");
    created_at = NULL;
    updated_at = NULL;
}

void
ModelRoute::cleanup() {


    if(start_time != nullptr) {
        delete start_time;
    }
    if(end_time != nullptr) {
        delete end_time;
    }
    if(number != nullptr) {
        delete number;
    }
    if(name != nullptr) {
        delete name;
    }
    if(created_at != nullptr) {
        delete created_at;
    }
    if(updated_at != nullptr) {
        delete updated_at;
    }
}

ModelRoute*
ModelRoute::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ModelRoute::fromJsonObject(QJsonObject &pJson) {
    ::api::setValue(&id, pJson["id"], "qint64", "");
    ::api::setValue(&comany_id, pJson["comany_id"], "qint64", "");
    ::api::setValue(&start_time, pJson["start_time"], "QString", "QString");
    ::api::setValue(&end_time, pJson["end_time"], "QString", "QString");
    ::api::setValue(&number, pJson["number"], "QString", "QString");
    ::api::setValue(&name, pJson["name"], "QString", "QString");
    ::api::setValue(&created_at, pJson["created_at"], "QDateTime", "QDateTime");
    ::api::setValue(&updated_at, pJson["updated_at"], "QDateTime", "QDateTime");
}

QString
ModelRoute::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
ModelRoute::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    obj->insert("id", QJsonValue(id));
    obj->insert("comany_id", QJsonValue(comany_id));
    toJsonValue(QString("start_time"), start_time, obj, QString("QString"));
    toJsonValue(QString("end_time"), end_time, obj, QString("QString"));
    toJsonValue(QString("number"), number, obj, QString("QString"));
    toJsonValue(QString("name"), name, obj, QString("QString"));
    toJsonValue(QString("created_at"), created_at, obj, QString("QDateTime"));
    toJsonValue(QString("updated_at"), updated_at, obj, QString("QDateTime"));

    return obj;
}

qint64
ModelRoute::getId() {
    return id;
}
void
ModelRoute::setId(qint64 id) {
    this->id = id;
}

qint64
ModelRoute::getComanyId() {
    return comany_id;
}
void
ModelRoute::setComanyId(qint64 comany_id) {
    this->comany_id = comany_id;
}

QString*
ModelRoute::getStartTime() {
    return start_time;
}
void
ModelRoute::setStartTime(QString* start_time) {
    this->start_time = start_time;
}

QString*
ModelRoute::getEndTime() {
    return end_time;
}
void
ModelRoute::setEndTime(QString* end_time) {
    this->end_time = end_time;
}

QString*
ModelRoute::getNumber() {
    return number;
}
void
ModelRoute::setNumber(QString* number) {
    this->number = number;
}

QString*
ModelRoute::getName() {
    return name;
}
void
ModelRoute::setName(QString* name) {
    this->name = name;
}

QDateTime*
ModelRoute::getCreatedAt() {
    return created_at;
}
void
ModelRoute::setCreatedAt(QDateTime* created_at) {
    this->created_at = created_at;
}

QDateTime*
ModelRoute::getUpdatedAt() {
    return updated_at;
}
void
ModelRoute::setUpdatedAt(QDateTime* updated_at) {
    this->updated_at = updated_at;
}


}

