/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ModelReceiptForm.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace api {

ModelReceiptForm::ModelReceiptForm(QString* json) {
    init();
    this->fromJson(*json);
}

ModelReceiptForm::ModelReceiptForm() {
    init();
}

ModelReceiptForm::~ModelReceiptForm() {
    this->cleanup();
}

void
ModelReceiptForm::init() {
    shifts = new QList<qint32>();
    date = NULL;
    user_id = 0L;
}

void
ModelReceiptForm::cleanup() {

    if(date != nullptr) {
        delete date;
    }

}

ModelReceiptForm*
ModelReceiptForm::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ModelReceiptForm::fromJsonObject(QJsonObject &pJson) {
    ::api::setValue(&shifts, pJson["shifts"], "QList", "qint32");
    ::api::setValue(&date, pJson["date"], "QDateTime", "QDateTime");
    ::api::setValue(&user_id, pJson["user_id"], "qint64", "");
}

QString
ModelReceiptForm::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
ModelReceiptForm::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    QJsonArray shiftsJsonArray;
    toJsonArray((QList<void*>*)shifts, &shiftsJsonArray, "shifts", "qint32");
    obj->insert("shifts", shiftsJsonArray);
    toJsonValue(QString("date"), date, obj, QString("QDateTime"));
    obj->insert("user_id", QJsonValue(user_id));

    return obj;
}

QList<qint32>*
ModelReceiptForm::getShifts() {
    return shifts;
}
void
ModelReceiptForm::setShifts(QList<qint32>* shifts) {
    this->shifts = shifts;
}

QDateTime*
ModelReceiptForm::getDate() {
    return date;
}
void
ModelReceiptForm::setDate(QDateTime* date) {
    this->date = date;
}

qint64
ModelReceiptForm::getUserId() {
    return user_id;
}
void
ModelReceiptForm::setUserId(qint64 user_id) {
    this->user_id = user_id;
}


}

