/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ModelTicketType.h
 * 
 * 
 */

#ifndef ModelTicketType_H_
#define ModelTicketType_H_

#include <QJsonObject>


#include "ModelTicketPrice.h"
#include <QDateTime>
#include <QList>
#include <QString>

#include "SWGObject.h"

namespace api {

class ModelTicketType: public SWGObject {
public:
    ModelTicketType();
    ModelTicketType(QString* json);
    virtual ~ModelTicketType();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    ModelTicketType* fromJson(QString &jsonString);

    qint64 getId();
    void setId(qint64 id);

    qint64 getComanyId();
    void setComanyId(qint64 comany_id);

    QString* getName();
    void setName(QString* name);

    QString* getDescription();
    void setDescription(QString* description);

    QString* getOrderCode();
    void setOrderCode(QString* order_code);

    QString* getSign();
    void setSign(QString* sign);

    QString* getSignForm();
    void setSignForm(QString* sign_form);

    QList<ModelTicketPrice*>* getTicketPrices();
    void setTicketPrices(QList<ModelTicketPrice*>* ticket_prices);

    QDateTime* getCreatedAt();
    void setCreatedAt(QDateTime* created_at);

    QDateTime* getUpdatedAt();
    void setUpdatedAt(QDateTime* updated_at);


private:
    qint64 id;
    qint64 comany_id;
    QString* name;
    QString* description;
    QString* order_code;
    QString* sign;
    QString* sign_form;
    QList<ModelTicketPrice*>* ticket_prices;
    QDateTime* created_at;
    QDateTime* updated_at;
};

}

#endif /* ModelTicketType_H_ */
