/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ModelChangePasswordUser.h
 * 
 * 
 */

#ifndef ModelChangePasswordUser_H_
#define ModelChangePasswordUser_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"

namespace api {

class ModelChangePasswordUser: public SWGObject {
public:
    ModelChangePasswordUser();
    ModelChangePasswordUser(QString* json);
    virtual ~ModelChangePasswordUser();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    ModelChangePasswordUser* fromJson(QString &jsonString);

    QString* getCurrentPassword();
    void setCurrentPassword(QString* current_password);

    QString* getNewPassword();
    void setNewPassword(QString* new_password);

    QString* getConfirmPassword();
    void setConfirmPassword(QString* confirm_password);


private:
    QString* current_password;
    QString* new_password;
    QString* confirm_password;
};

}

#endif /* ModelChangePasswordUser_H_ */
