/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ModelGPSRecord.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace api {

ModelGPSRecord::ModelGPSRecord(QString* json) {
    init();
    this->fromJson(*json);
}

ModelGPSRecord::ModelGPSRecord() {
    init();
}

ModelGPSRecord::~ModelGPSRecord() {
    this->cleanup();
}

void
ModelGPSRecord::init() {
    timestamp = 0L;
    lat = 0.0;
    lng = 0.0;
}

void
ModelGPSRecord::cleanup() {



}

ModelGPSRecord*
ModelGPSRecord::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ModelGPSRecord::fromJsonObject(QJsonObject &pJson) {
    ::api::setValue(&timestamp, pJson["timestamp"], "qint64", "");
    ::api::setValue(&lat, pJson["lat"], "double", "");
    ::api::setValue(&lng, pJson["lng"], "double", "");
}

QString
ModelGPSRecord::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
ModelGPSRecord::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    obj->insert("timestamp", QJsonValue(timestamp));
    obj->insert("lat", QJsonValue(lat));
    obj->insert("lng", QJsonValue(lng));

    return obj;
}

qint64
ModelGPSRecord::getTimestamp() {
    return timestamp;
}
void
ModelGPSRecord::setTimestamp(qint64 timestamp) {
    this->timestamp = timestamp;
}

double
ModelGPSRecord::getLat() {
    return lat;
}
void
ModelGPSRecord::setLat(double lat) {
    this->lat = lat;
}

double
ModelGPSRecord::getLng() {
    return lng;
}
void
ModelGPSRecord::setLng(double lng) {
    this->lng = lng;
}


}

