/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ModelRpRouteForm.h
 * 
 * 
 */

#ifndef ModelRpRouteForm_H_
#define ModelRpRouteForm_H_

#include <QJsonObject>


#include <QDateTime>

#include "SWGObject.h"

namespace api {

class ModelRpRouteForm: public SWGObject {
public:
    ModelRpRouteForm();
    ModelRpRouteForm(QString* json);
    virtual ~ModelRpRouteForm();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    ModelRpRouteForm* fromJson(QString &jsonString);

    QDateTime* getFromDate();
    void setFromDate(QDateTime* from_date);

    QDateTime* getToDate();
    void setToDate(QDateTime* to_date);


private:
    QDateTime* from_date;
    QDateTime* to_date;
};

}

#endif /* ModelRpRouteForm_H_ */
