/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ModelMembership.h
 * 
 * 
 */

#ifndef ModelMembership_H_
#define ModelMembership_H_

#include <QJsonObject>


#include "ModelSubscriptionType.h"
#include <QDateTime>
#include <QString>

#include "SWGObject.h"

namespace api {

class ModelMembership: public SWGObject {
public:
    ModelMembership();
    ModelMembership(QString* json);
    virtual ~ModelMembership();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    ModelMembership* fromJson(QString &jsonString);

    qint64 getId();
    void setId(qint64 id);

    qint64 getComanyId();
    void setComanyId(qint64 comany_id);

    QString* getRfid();
    void setRfid(QString* rfid);

    QString* getFullname();
    void setFullname(QString* fullname);

    QString* getAddress();
    void setAddress(QString* address);

    QString* getPhone();
    void setPhone(QString* phone);

    float getBalance();
    void setBalance(float balance);

    QString* getSidn();
    void setSidn(QString* sidn);

    QString* getEmail();
    void setEmail(QString* email);

    QString* getBarcode();
    void setBarcode(QString* barcode);

    QDateTime* getBirthday();
    void setBirthday(QDateTime* birthday);

    ModelSubscriptionType* getSubscriptionType();
    void setSubscriptionType(ModelSubscriptionType* subscription_type);

    QDateTime* getCreatedAt();
    void setCreatedAt(QDateTime* created_at);

    QDateTime* getUpdatedAt();
    void setUpdatedAt(QDateTime* updated_at);


private:
    qint64 id;
    qint64 comany_id;
    QString* rfid;
    QString* fullname;
    QString* address;
    QString* phone;
    float balance;
    QString* sidn;
    QString* email;
    QString* barcode;
    QDateTime* birthday;
    ModelSubscriptionType* subscription_type;
    QDateTime* created_at;
    QDateTime* updated_at;
};

}

#endif /* ModelMembership_H_ */
