/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ModelSubscriptionType.h
 * 
 * 
 */

#ifndef ModelSubscriptionType_H_
#define ModelSubscriptionType_H_

#include <QJsonObject>


#include <QDateTime>
#include <QString>

#include "SWGObject.h"

namespace api {

class ModelSubscriptionType: public SWGObject {
public:
    ModelSubscriptionType();
    ModelSubscriptionType(QString* json);
    virtual ~ModelSubscriptionType();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    ModelSubscriptionType* fromJson(QString &jsonString);

    qint64 getId();
    void setId(qint64 id);

    qint64 getComanyId();
    void setComanyId(qint64 comany_id);

    QString* getName();
    void setName(QString* name);

    QString* getDisplayName();
    void setDisplayName(QString* display_name);

    qint64 getDuration();
    void setDuration(qint64 duration);

    float getPrice();
    void setPrice(float price);

    QDateTime* getCreatedAt();
    void setCreatedAt(QDateTime* created_at);

    QDateTime* getUpdatedAt();
    void setUpdatedAt(QDateTime* updated_at);


private:
    qint64 id;
    qint64 comany_id;
    QString* name;
    QString* display_name;
    qint64 duration;
    float price;
    QDateTime* created_at;
    QDateTime* updated_at;
};

}

#endif /* ModelSubscriptionType_H_ */
