/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ModelCompany.h
 * 
 * 
 */

#ifndef ModelCompany_H_
#define ModelCompany_H_

#include <QJsonObject>


#include <QDateTime>
#include <QString>

#include "SWGObject.h"

namespace api {

class ModelCompany: public SWGObject {
public:
    ModelCompany();
    ModelCompany(QString* json);
    virtual ~ModelCompany();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    ModelCompany* fromJson(QString &jsonString);

    qint64 getId();
    void setId(qint64 id);

    QString* getName();
    void setName(QString* name);

    QString* getAddress();
    void setAddress(QString* address);

    QString* getTaxCode();
    void setTaxCode(QString* tax_code);

    QString* getPhone();
    void setPhone(QString* phone);

    QString* getLogo();
    void setLogo(QString* logo);

    QString* getEmail();
    void setEmail(QString* email);

    float getLat();
    void setLat(float lat);

    float getLng();
    void setLng(float lng);

    QDateTime* getCreatedAt();
    void setCreatedAt(QDateTime* created_at);

    QDateTime* getUpdatedAt();
    void setUpdatedAt(QDateTime* updated_at);


private:
    qint64 id;
    QString* name;
    QString* address;
    QString* tax_code;
    QString* phone;
    QString* logo;
    QString* email;
    float lat;
    float lng;
    QDateTime* created_at;
    QDateTime* updated_at;
};

}

#endif /* ModelCompany_H_ */
