/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ModelRpStaffForm.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace api {

ModelRpStaffForm::ModelRpStaffForm(QString* json) {
    init();
    this->fromJson(*json);
}

ModelRpStaffForm::ModelRpStaffForm() {
    init();
}

ModelRpStaffForm::~ModelRpStaffForm() {
    this->cleanup();
}

void
ModelRpStaffForm::init() {
    from_date = NULL;
    to_date = NULL;
    route_id = 0L;
    position = new QString("");
}

void
ModelRpStaffForm::cleanup() {
    if(from_date != nullptr) {
        delete from_date;
    }
    if(to_date != nullptr) {
        delete to_date;
    }

    if(position != nullptr) {
        delete position;
    }
}

ModelRpStaffForm*
ModelRpStaffForm::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ModelRpStaffForm::fromJsonObject(QJsonObject &pJson) {
    ::api::setValue(&from_date, pJson["from_date"], "QDateTime", "QDateTime");
    ::api::setValue(&to_date, pJson["to_date"], "QDateTime", "QDateTime");
    ::api::setValue(&route_id, pJson["route_id"], "qint64", "");
    ::api::setValue(&position, pJson["position"], "QString", "QString");
}

QString
ModelRpStaffForm::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
ModelRpStaffForm::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    toJsonValue(QString("from_date"), from_date, obj, QString("QDateTime"));
    toJsonValue(QString("to_date"), to_date, obj, QString("QDateTime"));
    obj->insert("route_id", QJsonValue(route_id));
    toJsonValue(QString("position"), position, obj, QString("QString"));

    return obj;
}

QDateTime*
ModelRpStaffForm::getFromDate() {
    return from_date;
}
void
ModelRpStaffForm::setFromDate(QDateTime* from_date) {
    this->from_date = from_date;
}

QDateTime*
ModelRpStaffForm::getToDate() {
    return to_date;
}
void
ModelRpStaffForm::setToDate(QDateTime* to_date) {
    this->to_date = to_date;
}

qint64
ModelRpStaffForm::getRouteId() {
    return route_id;
}
void
ModelRpStaffForm::setRouteId(qint64 route_id) {
    this->route_id = route_id;
}

QString*
ModelRpStaffForm::getPosition() {
    return position;
}
void
ModelRpStaffForm::setPosition(QString* position) {
    this->position = position;
}


}

