/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ModelBusStation.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace api {

ModelBusStation::ModelBusStation(QString* json) {
    init();
    this->fromJson(*json);
}

ModelBusStation::ModelBusStation() {
    init();
}

ModelBusStation::~ModelBusStation() {
    this->cleanup();
}

void
ModelBusStation::init() {
    id = 0L;
    name = new QString("");
    address = new QString("");
    lat = 0.0;
    lng = 0.0;
    created_at = NULL;
    updated_at = NULL;
}

void
ModelBusStation::cleanup() {

    if(name != nullptr) {
        delete name;
    }
    if(address != nullptr) {
        delete address;
    }


    if(created_at != nullptr) {
        delete created_at;
    }
    if(updated_at != nullptr) {
        delete updated_at;
    }
}

ModelBusStation*
ModelBusStation::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ModelBusStation::fromJsonObject(QJsonObject &pJson) {
    ::api::setValue(&id, pJson["id"], "qint64", "");
    ::api::setValue(&name, pJson["name"], "QString", "QString");
    ::api::setValue(&address, pJson["address"], "QString", "QString");
    ::api::setValue(&lat, pJson["lat"], "double", "");
    ::api::setValue(&lng, pJson["lng"], "double", "");
    ::api::setValue(&created_at, pJson["created_at"], "QDateTime", "QDateTime");
    ::api::setValue(&updated_at, pJson["updated_at"], "QDateTime", "QDateTime");
}

QString
ModelBusStation::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
ModelBusStation::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    obj->insert("id", QJsonValue(id));
    toJsonValue(QString("name"), name, obj, QString("QString"));
    toJsonValue(QString("address"), address, obj, QString("QString"));
    obj->insert("lat", QJsonValue(lat));
    obj->insert("lng", QJsonValue(lng));
    toJsonValue(QString("created_at"), created_at, obj, QString("QDateTime"));
    toJsonValue(QString("updated_at"), updated_at, obj, QString("QDateTime"));

    return obj;
}

qint64
ModelBusStation::getId() {
    return id;
}
void
ModelBusStation::setId(qint64 id) {
    this->id = id;
}

QString*
ModelBusStation::getName() {
    return name;
}
void
ModelBusStation::setName(QString* name) {
    this->name = name;
}

QString*
ModelBusStation::getAddress() {
    return address;
}
void
ModelBusStation::setAddress(QString* address) {
    this->address = address;
}

double
ModelBusStation::getLat() {
    return lat;
}
void
ModelBusStation::setLat(double lat) {
    this->lat = lat;
}

double
ModelBusStation::getLng() {
    return lng;
}
void
ModelBusStation::setLng(double lng) {
    this->lng = lng;
}

QDateTime*
ModelBusStation::getCreatedAt() {
    return created_at;
}
void
ModelBusStation::setCreatedAt(QDateTime* created_at) {
    this->created_at = created_at;
}

QDateTime*
ModelBusStation::getUpdatedAt() {
    return updated_at;
}
void
ModelBusStation::setUpdatedAt(QDateTime* updated_at) {
    this->updated_at = updated_at;
}


}

