/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ModelLoginView.h
 * 
 * 
 */

#ifndef ModelLoginView_H_
#define ModelLoginView_H_

#include <QJsonObject>


#include "ModelUser.h"
#include <QString>

#include "SWGObject.h"

namespace api {

class ModelLoginView: public SWGObject {
public:
    ModelLoginView();
    ModelLoginView(QString* json);
    virtual ~ModelLoginView();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    ModelLoginView* fromJson(QString &jsonString);

    QString* getToken();
    void setToken(QString* token);

    ModelUser* getUser();
    void setUser(ModelUser* user);


private:
    QString* token;
    ModelUser* user;
};

}

#endif /* ModelLoginView_H_ */
