/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ModelDevModel.h
 * 
 * 
 */

#ifndef ModelDevModel_H_
#define ModelDevModel_H_

#include <QJsonObject>


#include <QDateTime>
#include <QList>
#include <QString>

#include "SWGObject.h"

namespace api {

class ModelDevModel: public SWGObject {
public:
    ModelDevModel();
    ModelDevModel(QString* json);
    virtual ~ModelDevModel();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    ModelDevModel* fromJson(QString &jsonString);

    qint64 getId();
    void setId(qint64 id);

    QString* getName();
    void setName(QString* name);

    QString* getModel();
    void setModel(QString* model);

    QList<QString*>* getFeatures();
    void setFeatures(QList<QString*>* features);

    QDateTime* getCreatedAt();
    void setCreatedAt(QDateTime* created_at);

    QDateTime* getUpdatedAt();
    void setUpdatedAt(QDateTime* updated_at);


private:
    qint64 id;
    QString* name;
    QString* model;
    QList<QString*>* features;
    QDateTime* created_at;
    QDateTime* updated_at;
};

}

#endif /* ModelDevModel_H_ */
