/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ModelCollected.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace api {

ModelCollected::ModelCollected(QString* json) {
    init();
    this->fromJson(*json);
}

ModelCollected::ModelCollected() {
    init();
}

ModelCollected::~ModelCollected() {
    this->cleanup();
}

void
ModelCollected::init() {
    shifts = new QList<qint32>();
}

void
ModelCollected::cleanup() {

}

ModelCollected*
ModelCollected::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ModelCollected::fromJsonObject(QJsonObject &pJson) {
    ::api::setValue(&shifts, pJson["shifts"], "QList", "qint32");
}

QString
ModelCollected::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
ModelCollected::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    QJsonArray shiftsJsonArray;
    toJsonArray((QList<void*>*)shifts, &shiftsJsonArray, "shifts", "qint32");
    obj->insert("shifts", shiftsJsonArray);

    return obj;
}

QList<qint32>*
ModelCollected::getShifts() {
    return shifts;
}
void
ModelCollected::setShifts(QList<qint32>* shifts) {
    this->shifts = shifts;
}


}

