/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ModelPermissionForm.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace api {

ModelPermissionForm::ModelPermissionForm(QString* json) {
    init();
    this->fromJson(*json);
}

ModelPermissionForm::ModelPermissionForm() {
    init();
}

ModelPermissionForm::~ModelPermissionForm() {
    this->cleanup();
}

void
ModelPermissionForm::init() {
    id = 0L;
    display_name = new QString("");
    key = new QString("");
}

void
ModelPermissionForm::cleanup() {

    if(display_name != nullptr) {
        delete display_name;
    }
    if(key != nullptr) {
        delete key;
    }
}

ModelPermissionForm*
ModelPermissionForm::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ModelPermissionForm::fromJsonObject(QJsonObject &pJson) {
    ::api::setValue(&id, pJson["id"], "qint64", "");
    ::api::setValue(&display_name, pJson["display_name"], "QString", "QString");
    ::api::setValue(&key, pJson["key"], "QString", "QString");
}

QString
ModelPermissionForm::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
ModelPermissionForm::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    obj->insert("id", QJsonValue(id));
    toJsonValue(QString("display_name"), display_name, obj, QString("QString"));
    toJsonValue(QString("key"), key, obj, QString("QString"));

    return obj;
}

qint64
ModelPermissionForm::getId() {
    return id;
}
void
ModelPermissionForm::setId(qint64 id) {
    this->id = id;
}

QString*
ModelPermissionForm::getDisplayName() {
    return display_name;
}
void
ModelPermissionForm::setDisplayName(QString* display_name) {
    this->display_name = display_name;
}

QString*
ModelPermissionForm::getKey() {
    return key;
}
void
ModelPermissionForm::setKey(QString* key) {
    this->key = key;
}


}

