/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ModelUserSearch.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace api {

ModelUserSearch::ModelUserSearch(QString* json) {
    init();
    this->fromJson(*json);
}

ModelUserSearch::ModelUserSearch() {
    init();
}

ModelUserSearch::~ModelUserSearch() {
    this->cleanup();
}

void
ModelUserSearch::init() {
    rfid = new QString("");
    barcode = new QString("");
}

void
ModelUserSearch::cleanup() {
    if(rfid != nullptr) {
        delete rfid;
    }
    if(barcode != nullptr) {
        delete barcode;
    }
}

ModelUserSearch*
ModelUserSearch::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ModelUserSearch::fromJsonObject(QJsonObject &pJson) {
    ::api::setValue(&rfid, pJson["rfid"], "QString", "QString");
    ::api::setValue(&barcode, pJson["barcode"], "QString", "QString");
}

QString
ModelUserSearch::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
ModelUserSearch::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    toJsonValue(QString("rfid"), rfid, obj, QString("QString"));
    toJsonValue(QString("barcode"), barcode, obj, QString("QString"));

    return obj;
}

QString*
ModelUserSearch::getRfid() {
    return rfid;
}
void
ModelUserSearch::setRfid(QString* rfid) {
    this->rfid = rfid;
}

QString*
ModelUserSearch::getBarcode() {
    return barcode;
}
void
ModelUserSearch::setBarcode(QString* barcode) {
    this->barcode = barcode;
}


}

