/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ModelPermissionForm.h
 * 
 * 
 */

#ifndef ModelPermissionForm_H_
#define ModelPermissionForm_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"

namespace api {

class ModelPermissionForm: public SWGObject {
public:
    ModelPermissionForm();
    ModelPermissionForm(QString* json);
    virtual ~ModelPermissionForm();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    ModelPermissionForm* fromJson(QString &jsonString);

    qint64 getId();
    void setId(qint64 id);

    QString* getDisplayName();
    void setDisplayName(QString* display_name);

    QString* getKey();
    void setKey(QString* key);


private:
    qint64 id;
    QString* display_name;
    QString* key;
};

}

#endif /* ModelPermissionForm_H_ */
