/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ModelUserCreate.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace api {

ModelUserCreate::ModelUserCreate(QString* json) {
    init();
    this->fromJson(*json);
}

ModelUserCreate::ModelUserCreate() {
    init();
}

ModelUserCreate::~ModelUserCreate() {
    this->cleanup();
}

void
ModelUserCreate::init() {
    id = 0L;
    role_id = 0L;
    company_id = 0L;
    rfid = new QString("");
    username = new QString("");
    password = new QString("");
    confirm_password = new QString("");
    email = new QString("");
    fullname = new QString("");
    birthday = NULL;
    address = new QString("");
    sidn = new QString("");
    gender = 0;
    phone = new QString("");
}

void
ModelUserCreate::cleanup() {



    if(rfid != nullptr) {
        delete rfid;
    }
    if(username != nullptr) {
        delete username;
    }
    if(password != nullptr) {
        delete password;
    }
    if(confirm_password != nullptr) {
        delete confirm_password;
    }
    if(email != nullptr) {
        delete email;
    }
    if(fullname != nullptr) {
        delete fullname;
    }
    if(birthday != nullptr) {
        delete birthday;
    }
    if(address != nullptr) {
        delete address;
    }
    if(sidn != nullptr) {
        delete sidn;
    }

    if(phone != nullptr) {
        delete phone;
    }
}

ModelUserCreate*
ModelUserCreate::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ModelUserCreate::fromJsonObject(QJsonObject &pJson) {
    ::api::setValue(&id, pJson["id"], "qint64", "");
    ::api::setValue(&role_id, pJson["role_id"], "qint64", "");
    ::api::setValue(&company_id, pJson["company_id"], "qint64", "");
    ::api::setValue(&rfid, pJson["rfid"], "QString", "QString");
    ::api::setValue(&username, pJson["username"], "QString", "QString");
    ::api::setValue(&password, pJson["password"], "QString", "QString");
    ::api::setValue(&confirm_password, pJson["confirm_password"], "QString", "QString");
    ::api::setValue(&email, pJson["email"], "QString", "QString");
    ::api::setValue(&fullname, pJson["fullname"], "QString", "QString");
    ::api::setValue(&birthday, pJson["birthday"], "QDateTime", "QDateTime");
    ::api::setValue(&address, pJson["address"], "QString", "QString");
    ::api::setValue(&sidn, pJson["sidn"], "QString", "QString");
    ::api::setValue(&gender, pJson["gender"], "qint32", "");
    ::api::setValue(&phone, pJson["phone"], "QString", "QString");
}

QString
ModelUserCreate::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
ModelUserCreate::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    obj->insert("id", QJsonValue(id));
    obj->insert("role_id", QJsonValue(role_id));
    obj->insert("company_id", QJsonValue(company_id));
    toJsonValue(QString("rfid"), rfid, obj, QString("QString"));
    toJsonValue(QString("username"), username, obj, QString("QString"));
    toJsonValue(QString("password"), password, obj, QString("QString"));
    toJsonValue(QString("confirm_password"), confirm_password, obj, QString("QString"));
    toJsonValue(QString("email"), email, obj, QString("QString"));
    toJsonValue(QString("fullname"), fullname, obj, QString("QString"));
    toJsonValue(QString("birthday"), birthday, obj, QString("QDateTime"));
    toJsonValue(QString("address"), address, obj, QString("QString"));
    toJsonValue(QString("sidn"), sidn, obj, QString("QString"));
    obj->insert("gender", QJsonValue(gender));
    toJsonValue(QString("phone"), phone, obj, QString("QString"));

    return obj;
}

qint64
ModelUserCreate::getId() {
    return id;
}
void
ModelUserCreate::setId(qint64 id) {
    this->id = id;
}

qint64
ModelUserCreate::getRoleId() {
    return role_id;
}
void
ModelUserCreate::setRoleId(qint64 role_id) {
    this->role_id = role_id;
}

qint64
ModelUserCreate::getCompanyId() {
    return company_id;
}
void
ModelUserCreate::setCompanyId(qint64 company_id) {
    this->company_id = company_id;
}

QString*
ModelUserCreate::getRfid() {
    return rfid;
}
void
ModelUserCreate::setRfid(QString* rfid) {
    this->rfid = rfid;
}

QString*
ModelUserCreate::getUsername() {
    return username;
}
void
ModelUserCreate::setUsername(QString* username) {
    this->username = username;
}

QString*
ModelUserCreate::getPassword() {
    return password;
}
void
ModelUserCreate::setPassword(QString* password) {
    this->password = password;
}

QString*
ModelUserCreate::getConfirmPassword() {
    return confirm_password;
}
void
ModelUserCreate::setConfirmPassword(QString* confirm_password) {
    this->confirm_password = confirm_password;
}

QString*
ModelUserCreate::getEmail() {
    return email;
}
void
ModelUserCreate::setEmail(QString* email) {
    this->email = email;
}

QString*
ModelUserCreate::getFullname() {
    return fullname;
}
void
ModelUserCreate::setFullname(QString* fullname) {
    this->fullname = fullname;
}

QDateTime*
ModelUserCreate::getBirthday() {
    return birthday;
}
void
ModelUserCreate::setBirthday(QDateTime* birthday) {
    this->birthday = birthday;
}

QString*
ModelUserCreate::getAddress() {
    return address;
}
void
ModelUserCreate::setAddress(QString* address) {
    this->address = address;
}

QString*
ModelUserCreate::getSidn() {
    return sidn;
}
void
ModelUserCreate::setSidn(QString* sidn) {
    this->sidn = sidn;
}

qint32
ModelUserCreate::getGender() {
    return gender;
}
void
ModelUserCreate::setGender(qint32 gender) {
    this->gender = gender;
}

QString*
ModelUserCreate::getPhone() {
    return phone;
}
void
ModelUserCreate::setPhone(QString* phone) {
    this->phone = phone;
}


}

