/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ModelCompany.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace api {

ModelCompany::ModelCompany(QString* json) {
    init();
    this->fromJson(*json);
}

ModelCompany::ModelCompany() {
    init();
}

ModelCompany::~ModelCompany() {
    this->cleanup();
}

void
ModelCompany::init() {
    id = 0L;
    name = new QString("");
    address = new QString("");
    tax_code = new QString("");
    phone = new QString("");
    logo = new QString("");
    email = new QString("");
    lat = 0.0f;
    lng = 0.0f;
    created_at = NULL;
    updated_at = NULL;
}

void
ModelCompany::cleanup() {

    if(name != nullptr) {
        delete name;
    }
    if(address != nullptr) {
        delete address;
    }
    if(tax_code != nullptr) {
        delete tax_code;
    }
    if(phone != nullptr) {
        delete phone;
    }
    if(logo != nullptr) {
        delete logo;
    }
    if(email != nullptr) {
        delete email;
    }


    if(created_at != nullptr) {
        delete created_at;
    }
    if(updated_at != nullptr) {
        delete updated_at;
    }
}

ModelCompany*
ModelCompany::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ModelCompany::fromJsonObject(QJsonObject &pJson) {
    ::api::setValue(&id, pJson["id"], "qint64", "");
    ::api::setValue(&name, pJson["name"], "QString", "QString");
    ::api::setValue(&address, pJson["address"], "QString", "QString");
    ::api::setValue(&tax_code, pJson["tax_code"], "QString", "QString");
    ::api::setValue(&phone, pJson["phone"], "QString", "QString");
    ::api::setValue(&logo, pJson["logo"], "QString", "QString");
    ::api::setValue(&email, pJson["email"], "QString", "QString");
    ::api::setValue(&lat, pJson["lat"], "float", "");
    ::api::setValue(&lng, pJson["lng"], "float", "");
    ::api::setValue(&created_at, pJson["created_at"], "QDateTime", "QDateTime");
    ::api::setValue(&updated_at, pJson["updated_at"], "QDateTime", "QDateTime");
}

QString
ModelCompany::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
ModelCompany::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    obj->insert("id", QJsonValue(id));
    toJsonValue(QString("name"), name, obj, QString("QString"));
    toJsonValue(QString("address"), address, obj, QString("QString"));
    toJsonValue(QString("tax_code"), tax_code, obj, QString("QString"));
    toJsonValue(QString("phone"), phone, obj, QString("QString"));
    toJsonValue(QString("logo"), logo, obj, QString("QString"));
    toJsonValue(QString("email"), email, obj, QString("QString"));
    obj->insert("lat", QJsonValue(lat));
    obj->insert("lng", QJsonValue(lng));
    toJsonValue(QString("created_at"), created_at, obj, QString("QDateTime"));
    toJsonValue(QString("updated_at"), updated_at, obj, QString("QDateTime"));

    return obj;
}

qint64
ModelCompany::getId() {
    return id;
}
void
ModelCompany::setId(qint64 id) {
    this->id = id;
}

QString*
ModelCompany::getName() {
    return name;
}
void
ModelCompany::setName(QString* name) {
    this->name = name;
}

QString*
ModelCompany::getAddress() {
    return address;
}
void
ModelCompany::setAddress(QString* address) {
    this->address = address;
}

QString*
ModelCompany::getTaxCode() {
    return tax_code;
}
void
ModelCompany::setTaxCode(QString* tax_code) {
    this->tax_code = tax_code;
}

QString*
ModelCompany::getPhone() {
    return phone;
}
void
ModelCompany::setPhone(QString* phone) {
    this->phone = phone;
}

QString*
ModelCompany::getLogo() {
    return logo;
}
void
ModelCompany::setLogo(QString* logo) {
    this->logo = logo;
}

QString*
ModelCompany::getEmail() {
    return email;
}
void
ModelCompany::setEmail(QString* email) {
    this->email = email;
}

float
ModelCompany::getLat() {
    return lat;
}
void
ModelCompany::setLat(float lat) {
    this->lat = lat;
}

float
ModelCompany::getLng() {
    return lng;
}
void
ModelCompany::setLng(float lng) {
    this->lng = lng;
}

QDateTime*
ModelCompany::getCreatedAt() {
    return created_at;
}
void
ModelCompany::setCreatedAt(QDateTime* created_at) {
    this->created_at = created_at;
}

QDateTime*
ModelCompany::getUpdatedAt() {
    return updated_at;
}
void
ModelCompany::setUpdatedAt(QDateTime* updated_at) {
    this->updated_at = updated_at;
}


}

