/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ModelRouteForm.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace api {

ModelRouteForm::ModelRouteForm(QString* json) {
    init();
    this->fromJson(*json);
}

ModelRouteForm::ModelRouteForm() {
    init();
}

ModelRouteForm::~ModelRouteForm() {
    this->cleanup();
}

void
ModelRouteForm::init() {
    id = 0L;
    start_time = new QString("");
    end_time = new QString("");
    number = 0L;
    name = new QString("");
    bus_stations = new QList<ModelBusStation*>();
}

void
ModelRouteForm::cleanup() {

    if(start_time != nullptr) {
        delete start_time;
    }
    if(end_time != nullptr) {
        delete end_time;
    }

    if(name != nullptr) {
        delete name;
    }
    if(bus_stations != nullptr) {
        QList<ModelBusStation*>* arr = bus_stations;
        foreach(ModelBusStation* o, *arr) {
            delete o;
        }
        delete bus_stations;
    }
}

ModelRouteForm*
ModelRouteForm::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ModelRouteForm::fromJsonObject(QJsonObject &pJson) {
    ::api::setValue(&id, pJson["id"], "qint64", "");
    ::api::setValue(&start_time, pJson["start_time"], "QString", "QString");
    ::api::setValue(&end_time, pJson["end_time"], "QString", "QString");
    ::api::setValue(&number, pJson["number"], "qint64", "");
    ::api::setValue(&name, pJson["name"], "QString", "QString");
    ::api::setValue(&bus_stations, pJson["bus_stations"], "QList", "ModelBusStation");
}

QString
ModelRouteForm::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
ModelRouteForm::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    obj->insert("id", QJsonValue(id));
    toJsonValue(QString("start_time"), start_time, obj, QString("QString"));
    toJsonValue(QString("end_time"), end_time, obj, QString("QString"));
    obj->insert("number", QJsonValue(number));
    toJsonValue(QString("name"), name, obj, QString("QString"));
    QJsonArray bus_stationsJsonArray;
    toJsonArray((QList<void*>*)bus_stations, &bus_stationsJsonArray, "bus_stations", "ModelBusStation");
    obj->insert("bus_stations", bus_stationsJsonArray);

    return obj;
}

qint64
ModelRouteForm::getId() {
    return id;
}
void
ModelRouteForm::setId(qint64 id) {
    this->id = id;
}

QString*
ModelRouteForm::getStartTime() {
    return start_time;
}
void
ModelRouteForm::setStartTime(QString* start_time) {
    this->start_time = start_time;
}

QString*
ModelRouteForm::getEndTime() {
    return end_time;
}
void
ModelRouteForm::setEndTime(QString* end_time) {
    this->end_time = end_time;
}

qint64
ModelRouteForm::getNumber() {
    return number;
}
void
ModelRouteForm::setNumber(qint64 number) {
    this->number = number;
}

QString*
ModelRouteForm::getName() {
    return name;
}
void
ModelRouteForm::setName(QString* name) {
    this->name = name;
}

QList<ModelBusStation*>*
ModelRouteForm::getBusStations() {
    return bus_stations;
}
void
ModelRouteForm::setBusStations(QList<ModelBusStation*>* bus_stations) {
    this->bus_stations = bus_stations;
}


}

