/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ModelMachineLoginView.h
 * 
 * 
 */

#ifndef ModelMachineLoginView_H_
#define ModelMachineLoginView_H_

#include <QJsonObject>


#include "ModelDevice.h"
#include "ModelUser.h"
#include "ModelVehicle.h"
#include <QDateTime>
#include <QString>

#include "SWGObject.h"

namespace api {

class ModelMachineLoginView: public SWGObject {
public:
    ModelMachineLoginView();
    ModelMachineLoginView(QString* json);
    virtual ~ModelMachineLoginView();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    ModelMachineLoginView* fromJson(QString &jsonString);

    ModelUser* getUser();
    void setUser(ModelUser* user);

    ModelVehicle* getVehicle();
    void setVehicle(ModelVehicle* vehicle);

    ModelDevice* getDevice();
    void setDevice(ModelDevice* device);

    QDateTime* getStarted();
    void setStarted(QDateTime* started);

    QString* getShiftToken();
    void setShiftToken(QString* shift_token);


private:
    ModelUser* user;
    ModelVehicle* vehicle;
    ModelDevice* device;
    QDateTime* started;
    QString* shift_token;
};

}

#endif /* ModelMachineLoginView_H_ */
