/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ModelPermission.h
 * 
 * 
 */

#ifndef ModelPermission_H_
#define ModelPermission_H_

#include <QJsonObject>


#include <QDateTime>
#include <QString>

#include "SWGObject.h"

namespace api {

class ModelPermission: public SWGObject {
public:
    ModelPermission();
    ModelPermission(QString* json);
    virtual ~ModelPermission();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    ModelPermission* fromJson(QString &jsonString);

    qint64 getId();
    void setId(qint64 id);

    QString* getDisplayName();
    void setDisplayName(QString* display_name);

    QString* getKey();
    void setKey(QString* key);

    QDateTime* getCreatedAt();
    void setCreatedAt(QDateTime* created_at);

    QDateTime* getUpdatedAt();
    void setUpdatedAt(QDateTime* updated_at);


private:
    qint64 id;
    QString* display_name;
    QString* key;
    QDateTime* created_at;
    QDateTime* updated_at;
};

}

#endif /* ModelPermission_H_ */
