/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ModelSubscriptionTypeForm.h
 * 
 * 
 */

#ifndef ModelSubscriptionTypeForm_H_
#define ModelSubscriptionTypeForm_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"

namespace api {

class ModelSubscriptionTypeForm: public SWGObject {
public:
    ModelSubscriptionTypeForm();
    ModelSubscriptionTypeForm(QString* json);
    virtual ~ModelSubscriptionTypeForm();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    ModelSubscriptionTypeForm* fromJson(QString &jsonString);

    qint64 getId();
    void setId(qint64 id);

    qint64 getComanyId();
    void setComanyId(qint64 comany_id);

    QString* getName();
    void setName(QString* name);

    QString* getDisplayName();
    void setDisplayName(QString* display_name);

    qint64 getDuration();
    void setDuration(qint64 duration);

    float getPrice();
    void setPrice(float price);


private:
    qint64 id;
    qint64 comany_id;
    QString* name;
    QString* display_name;
    qint64 duration;
    float price;
};

}

#endif /* ModelSubscriptionTypeForm_H_ */
