/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ModelReceiptForm.h
 * 
 * 
 */

#ifndef ModelReceiptForm_H_
#define ModelReceiptForm_H_

#include <QJsonObject>


#include <QDateTime>
#include <QList>

#include "SWGObject.h"

namespace api {

class ModelReceiptForm: public SWGObject {
public:
    ModelReceiptForm();
    ModelReceiptForm(QString* json);
    virtual ~ModelReceiptForm();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    ModelReceiptForm* fromJson(QString &jsonString);

    QList<qint32>* getShifts();
    void setShifts(QList<qint32>* shifts);

    QDateTime* getDate();
    void setDate(QDateTime* date);

    qint64 getUserId();
    void setUserId(qint64 user_id);


private:
    QList<qint32>* shifts;
    QDateTime* date;
    qint64 user_id;
};

}

#endif /* ModelReceiptForm_H_ */
