/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ModelGenericResponse.h
 * 
 * 
 */

#ifndef ModelGenericResponse_H_
#define ModelGenericResponse_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"

namespace api {

class ModelGenericResponse: public SWGObject {
public:
    ModelGenericResponse();
    ModelGenericResponse(QString* json);
    virtual ~ModelGenericResponse();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    ModelGenericResponse* fromJson(QString &jsonString);

    bool isStatus();
    void setStatus(bool status);

    QString* getMessage();
    void setMessage(QString* message);


private:
    bool status;
    QString* message;
};

}

#endif /* ModelGenericResponse_H_ */
