/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ModelCompanyCreate.h
 * 
 * 
 */

#ifndef ModelCompanyCreate_H_
#define ModelCompanyCreate_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"

namespace api {

class ModelCompanyCreate: public SWGObject {
public:
    ModelCompanyCreate();
    ModelCompanyCreate(QString* json);
    virtual ~ModelCompanyCreate();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    ModelCompanyCreate* fromJson(QString &jsonString);

    qint64 getId();
    void setId(qint64 id);

    QString* getName();
    void setName(QString* name);

    QString* getAddress();
    void setAddress(QString* address);

    QString* getTaxCode();
    void setTaxCode(QString* tax_code);

    QString* getPhone();
    void setPhone(QString* phone);

    QString* getLogo();
    void setLogo(QString* logo);

    QString* getEmail();
    void setEmail(QString* email);

    QString* getUsername();
    void setUsername(QString* username);

    QString* getPassword();
    void setPassword(QString* password);

    float getLat();
    void setLat(float lat);

    float getLng();
    void setLng(float lng);


private:
    qint64 id;
    QString* name;
    QString* address;
    QString* tax_code;
    QString* phone;
    QString* logo;
    QString* email;
    QString* username;
    QString* password;
    float lat;
    float lng;
};

}

#endif /* ModelCompanyCreate_H_ */
