/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ModelRoute.h
 * 
 * 
 */

#ifndef ModelRoute_H_
#define ModelRoute_H_

#include <QJsonObject>


#include <QDateTime>
#include <QString>

#include "SWGObject.h"

namespace api {

class ModelRoute: public SWGObject {
public:
    ModelRoute();
    ModelRoute(QString* json);
    virtual ~ModelRoute();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    ModelRoute* fromJson(QString &jsonString);

    qint64 getId();
    void setId(qint64 id);

    qint64 getComanyId();
    void setComanyId(qint64 comany_id);

    QString* getStartTime();
    void setStartTime(QString* start_time);

    QString* getEndTime();
    void setEndTime(QString* end_time);

    QString* getNumber();
    void setNumber(QString* number);

    QString* getName();
    void setName(QString* name);

    QDateTime* getCreatedAt();
    void setCreatedAt(QDateTime* created_at);

    QDateTime* getUpdatedAt();
    void setUpdatedAt(QDateTime* updated_at);


private:
    qint64 id;
    qint64 comany_id;
    QString* start_time;
    QString* end_time;
    QString* number;
    QString* name;
    QDateTime* created_at;
    QDateTime* updated_at;
};

}

#endif /* ModelRoute_H_ */
