/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ModelReceiptView.h
 * 
 * 
 */

#ifndef ModelReceiptView_H_
#define ModelReceiptView_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"

namespace api {

class ModelReceiptView: public SWGObject {
public:
    ModelReceiptView();
    ModelReceiptView(QString* json);
    virtual ~ModelReceiptView();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    ModelReceiptView* fromJson(QString &jsonString);

    qint64 getShiftId();
    void setShiftId(qint64 shift_id);

    QString* getLicensePlates();
    void setLicensePlates(QString* license_plates);

    QString* getDriverName();
    void setDriverName(QString* driver_name);

    QString* getSubdriverName();
    void setSubdriverName(QString* subdriver_name);

    QString* getRouteName();
    void setRouteName(QString* route_name);

    QString* getDateTime();
    void setDateTime(QString* date_time);

    float getTotalPrice();
    void setTotalPrice(float total_price);

    qint32 getCollected();
    void setCollected(qint32 collected);


private:
    qint64 shift_id;
    QString* license_plates;
    QString* driver_name;
    QString* subdriver_name;
    QString* route_name;
    QString* date_time;
    float total_price;
    qint32 collected;
};

}

#endif /* ModelReceiptView_H_ */
