/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ModelPermission.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace api {

ModelPermission::ModelPermission(QString* json) {
    init();
    this->fromJson(*json);
}

ModelPermission::ModelPermission() {
    init();
}

ModelPermission::~ModelPermission() {
    this->cleanup();
}

void
ModelPermission::init() {
    id = 0L;
    display_name = new QString("");
    key = new QString("");
    created_at = NULL;
    updated_at = NULL;
}

void
ModelPermission::cleanup() {

    if(display_name != nullptr) {
        delete display_name;
    }
    if(key != nullptr) {
        delete key;
    }
    if(created_at != nullptr) {
        delete created_at;
    }
    if(updated_at != nullptr) {
        delete updated_at;
    }
}

ModelPermission*
ModelPermission::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ModelPermission::fromJsonObject(QJsonObject &pJson) {
    ::api::setValue(&id, pJson["id"], "qint64", "");
    ::api::setValue(&display_name, pJson["display_name"], "QString", "QString");
    ::api::setValue(&key, pJson["key"], "QString", "QString");
    ::api::setValue(&created_at, pJson["created_at"], "QDateTime", "QDateTime");
    ::api::setValue(&updated_at, pJson["updated_at"], "QDateTime", "QDateTime");
}

QString
ModelPermission::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
ModelPermission::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    obj->insert("id", QJsonValue(id));
    toJsonValue(QString("display_name"), display_name, obj, QString("QString"));
    toJsonValue(QString("key"), key, obj, QString("QString"));
    toJsonValue(QString("created_at"), created_at, obj, QString("QDateTime"));
    toJsonValue(QString("updated_at"), updated_at, obj, QString("QDateTime"));

    return obj;
}

qint64
ModelPermission::getId() {
    return id;
}
void
ModelPermission::setId(qint64 id) {
    this->id = id;
}

QString*
ModelPermission::getDisplayName() {
    return display_name;
}
void
ModelPermission::setDisplayName(QString* display_name) {
    this->display_name = display_name;
}

QString*
ModelPermission::getKey() {
    return key;
}
void
ModelPermission::setKey(QString* key) {
    this->key = key;
}

QDateTime*
ModelPermission::getCreatedAt() {
    return created_at;
}
void
ModelPermission::setCreatedAt(QDateTime* created_at) {
    this->created_at = created_at;
}

QDateTime*
ModelPermission::getUpdatedAt() {
    return updated_at;
}
void
ModelPermission::setUpdatedAt(QDateTime* updated_at) {
    this->updated_at = updated_at;
}


}

