/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ModelDevice.h
 * 
 * 
 */

#ifndef ModelDevice_H_
#define ModelDevice_H_

#include <QJsonObject>


#include "ModelCompany.h"
#include "ModelDevModel.h"
#include <QDateTime>
#include <QString>

#include "SWGObject.h"

namespace api {

class ModelDevice: public SWGObject {
public:
    ModelDevice();
    ModelDevice(QString* json);
    virtual ~ModelDevice();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    ModelDevice* fromJson(QString &jsonString);

    qint64 getId();
    void setId(qint64 id);

    ModelDevModel* getDeviceModel();
    void setDeviceModel(ModelDevModel* device_model);

    ModelCompany* getCompany();
    void setCompany(ModelCompany* company);

    QString* getIdentity();
    void setIdentity(QString* identity);

    qint32 getIsRunning();
    void setIsRunning(qint32 is_running);

    qint64 getVersion();
    void setVersion(qint64 version);

    float getLat();
    void setLat(float lat);

    float getLng();
    void setLng(float lng);

    QDateTime* getCreatedAt();
    void setCreatedAt(QDateTime* created_at);

    QDateTime* getUpdatedAt();
    void setUpdatedAt(QDateTime* updated_at);


private:
    qint64 id;
    ModelDevModel* device_model;
    ModelCompany* company;
    QString* identity;
    qint32 is_running;
    qint64 version;
    float lat;
    float lng;
    QDateTime* created_at;
    QDateTime* updated_at;
};

}

#endif /* ModelDevice_H_ */
