/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ModelMembershipForm.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace api {

ModelMembershipForm::ModelMembershipForm(QString* json) {
    init();
    this->fromJson(*json);
}

ModelMembershipForm::ModelMembershipForm() {
    init();
}

ModelMembershipForm::~ModelMembershipForm() {
    this->cleanup();
}

void
ModelMembershipForm::init() {
    id = 0L;
    comany_id = 0L;
    subscription_type_id = 0L;
    rfid = new QString("");
    fullname = new QString("");
    address = new QString("");
    phone = new QString("");
    balance = 0.0f;
    sidn = new QString("");
    email = new QString("");
    barcode = new QString("");
    birthday = NULL;
}

void
ModelMembershipForm::cleanup() {



    if(rfid != nullptr) {
        delete rfid;
    }
    if(fullname != nullptr) {
        delete fullname;
    }
    if(address != nullptr) {
        delete address;
    }
    if(phone != nullptr) {
        delete phone;
    }

    if(sidn != nullptr) {
        delete sidn;
    }
    if(email != nullptr) {
        delete email;
    }
    if(barcode != nullptr) {
        delete barcode;
    }
    if(birthday != nullptr) {
        delete birthday;
    }
}

ModelMembershipForm*
ModelMembershipForm::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ModelMembershipForm::fromJsonObject(QJsonObject &pJson) {
    ::api::setValue(&id, pJson["id"], "qint64", "");
    ::api::setValue(&comany_id, pJson["comany_id"], "qint64", "");
    ::api::setValue(&subscription_type_id, pJson["subscription_type_id"], "qint64", "");
    ::api::setValue(&rfid, pJson["rfid"], "QString", "QString");
    ::api::setValue(&fullname, pJson["fullname"], "QString", "QString");
    ::api::setValue(&address, pJson["address"], "QString", "QString");
    ::api::setValue(&phone, pJson["phone"], "QString", "QString");
    ::api::setValue(&balance, pJson["balance"], "float", "");
    ::api::setValue(&sidn, pJson["sidn"], "QString", "QString");
    ::api::setValue(&email, pJson["email"], "QString", "QString");
    ::api::setValue(&barcode, pJson["barcode"], "QString", "QString");
    ::api::setValue(&birthday, pJson["birthday"], "QDateTime", "QDateTime");
}

QString
ModelMembershipForm::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
ModelMembershipForm::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    obj->insert("id", QJsonValue(id));
    obj->insert("comany_id", QJsonValue(comany_id));
    obj->insert("subscription_type_id", QJsonValue(subscription_type_id));
    toJsonValue(QString("rfid"), rfid, obj, QString("QString"));
    toJsonValue(QString("fullname"), fullname, obj, QString("QString"));
    toJsonValue(QString("address"), address, obj, QString("QString"));
    toJsonValue(QString("phone"), phone, obj, QString("QString"));
    obj->insert("balance", QJsonValue(balance));
    toJsonValue(QString("sidn"), sidn, obj, QString("QString"));
    toJsonValue(QString("email"), email, obj, QString("QString"));
    toJsonValue(QString("barcode"), barcode, obj, QString("QString"));
    toJsonValue(QString("birthday"), birthday, obj, QString("QDateTime"));

    return obj;
}

qint64
ModelMembershipForm::getId() {
    return id;
}
void
ModelMembershipForm::setId(qint64 id) {
    this->id = id;
}

qint64
ModelMembershipForm::getComanyId() {
    return comany_id;
}
void
ModelMembershipForm::setComanyId(qint64 comany_id) {
    this->comany_id = comany_id;
}

qint64
ModelMembershipForm::getSubscriptionTypeId() {
    return subscription_type_id;
}
void
ModelMembershipForm::setSubscriptionTypeId(qint64 subscription_type_id) {
    this->subscription_type_id = subscription_type_id;
}

QString*
ModelMembershipForm::getRfid() {
    return rfid;
}
void
ModelMembershipForm::setRfid(QString* rfid) {
    this->rfid = rfid;
}

QString*
ModelMembershipForm::getFullname() {
    return fullname;
}
void
ModelMembershipForm::setFullname(QString* fullname) {
    this->fullname = fullname;
}

QString*
ModelMembershipForm::getAddress() {
    return address;
}
void
ModelMembershipForm::setAddress(QString* address) {
    this->address = address;
}

QString*
ModelMembershipForm::getPhone() {
    return phone;
}
void
ModelMembershipForm::setPhone(QString* phone) {
    this->phone = phone;
}

float
ModelMembershipForm::getBalance() {
    return balance;
}
void
ModelMembershipForm::setBalance(float balance) {
    this->balance = balance;
}

QString*
ModelMembershipForm::getSidn() {
    return sidn;
}
void
ModelMembershipForm::setSidn(QString* sidn) {
    this->sidn = sidn;
}

QString*
ModelMembershipForm::getEmail() {
    return email;
}
void
ModelMembershipForm::setEmail(QString* email) {
    this->email = email;
}

QString*
ModelMembershipForm::getBarcode() {
    return barcode;
}
void
ModelMembershipForm::setBarcode(QString* barcode) {
    this->barcode = barcode;
}

QDateTime*
ModelMembershipForm::getBirthday() {
    return birthday;
}
void
ModelMembershipForm::setBirthday(QDateTime* birthday) {
    this->birthday = birthday;
}


}

