/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ModelUser.h
 * 
 * 
 */

#ifndef ModelUser_H_
#define ModelUser_H_

#include <QJsonObject>


#include "ModelCompany.h"
#include "ModelPermission.h"
#include "ModelRfidCard.h"
#include "ModelRole.h"
#include <QDateTime>
#include <QList>
#include <QString>

#include "SWGObject.h"

namespace api {

class ModelUser: public SWGObject {
public:
    ModelUser();
    ModelUser(QString* json);
    virtual ~ModelUser();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    ModelUser* fromJson(QString &jsonString);

    qint64 getId();
    void setId(qint64 id);

    qint64 getRoleId();
    void setRoleId(qint64 role_id);

    ModelRole* getRole();
    void setRole(ModelRole* role);

    qint64 getCompanyId();
    void setCompanyId(qint64 company_id);

    ModelCompany* getCompany();
    void setCompany(ModelCompany* company);

    QList<ModelPermission*>* getPermissions();
    void setPermissions(QList<ModelPermission*>* permissions);

    qint64 getPinCode();
    void setPinCode(qint64 pin_code);

    qint64 getRfidcardId();
    void setRfidcardId(qint64 rfidcard_id);

    ModelRfidCard* getRfidcard();
    void setRfidcard(ModelRfidCard* rfidcard);

    QString* getUsername();
    void setUsername(QString* username);

    QString* getEmail();
    void setEmail(QString* email);

    QString* getFullname();
    void setFullname(QString* fullname);

    QDateTime* getBirthday();
    void setBirthday(QDateTime* birthday);

    QString* getAddress();
    void setAddress(QString* address);

    QString* getSidn();
    void setSidn(QString* sidn);

    qint32 getGender();
    void setGender(qint32 gender);

    QString* getPhone();
    void setPhone(QString* phone);

    QDateTime* getCreatedAt();
    void setCreatedAt(QDateTime* created_at);

    QDateTime* getUpdatedAt();
    void setUpdatedAt(QDateTime* updated_at);


private:
    qint64 id;
    qint64 role_id;
    ModelRole* role;
    qint64 company_id;
    ModelCompany* company;
    QList<ModelPermission*>* permissions;
    qint64 pin_code;
    qint64 rfidcard_id;
    ModelRfidCard* rfidcard;
    QString* username;
    QString* email;
    QString* fullname;
    QDateTime* birthday;
    QString* address;
    QString* sidn;
    qint32 gender;
    QString* phone;
    QDateTime* created_at;
    QDateTime* updated_at;
};

}

#endif /* ModelUser_H_ */
