/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ModelChangePasswordUser.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace api {

ModelChangePasswordUser::ModelChangePasswordUser(QString* json) {
    init();
    this->fromJson(*json);
}

ModelChangePasswordUser::ModelChangePasswordUser() {
    init();
}

ModelChangePasswordUser::~ModelChangePasswordUser() {
    this->cleanup();
}

void
ModelChangePasswordUser::init() {
    current_password = new QString("");
    new_password = new QString("");
    confirm_password = new QString("");
}

void
ModelChangePasswordUser::cleanup() {
    if(current_password != nullptr) {
        delete current_password;
    }
    if(new_password != nullptr) {
        delete new_password;
    }
    if(confirm_password != nullptr) {
        delete confirm_password;
    }
}

ModelChangePasswordUser*
ModelChangePasswordUser::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ModelChangePasswordUser::fromJsonObject(QJsonObject &pJson) {
    ::api::setValue(&current_password, pJson["current_password"], "QString", "QString");
    ::api::setValue(&new_password, pJson["new_password"], "QString", "QString");
    ::api::setValue(&confirm_password, pJson["confirm_password"], "QString", "QString");
}

QString
ModelChangePasswordUser::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
ModelChangePasswordUser::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    toJsonValue(QString("current_password"), current_password, obj, QString("QString"));
    toJsonValue(QString("new_password"), new_password, obj, QString("QString"));
    toJsonValue(QString("confirm_password"), confirm_password, obj, QString("QString"));

    return obj;
}

QString*
ModelChangePasswordUser::getCurrentPassword() {
    return current_password;
}
void
ModelChangePasswordUser::setCurrentPassword(QString* current_password) {
    this->current_password = current_password;
}

QString*
ModelChangePasswordUser::getNewPassword() {
    return new_password;
}
void
ModelChangePasswordUser::setNewPassword(QString* new_password) {
    this->new_password = new_password;
}

QString*
ModelChangePasswordUser::getConfirmPassword() {
    return confirm_password;
}
void
ModelChangePasswordUser::setConfirmPassword(QString* confirm_password) {
    this->confirm_password = confirm_password;
}


}

