/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ModelUpdateAction.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace api {

ModelUpdateAction::ModelUpdateAction(QString* json) {
    init();
    this->fromJson(*json);
}

ModelUpdateAction::ModelUpdateAction() {
    init();
}

ModelUpdateAction::~ModelUpdateAction() {
    this->cleanup();
}

void
ModelUpdateAction::init() {
    id = 0;
    action = new QString("");
    subject_data = new QString("");
    subject_type = new QString("");
}

void
ModelUpdateAction::cleanup() {

    if(action != nullptr) {
        delete action;
    }
    if(subject_data != nullptr) {
        delete subject_data;
    }
    if(subject_type != nullptr) {
        delete subject_type;
    }
}

ModelUpdateAction*
ModelUpdateAction::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ModelUpdateAction::fromJsonObject(QJsonObject &pJson) {
    ::api::setValue(&id, pJson["id"], "qint32", "");
    ::api::setValue(&action, pJson["action"], "QString", "QString");
    ::api::setValue(&subject_data, pJson["subject_data"], "QString", "QString");
    ::api::setValue(&subject_type, pJson["subject_type"], "QString", "QString");
}

QString
ModelUpdateAction::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
ModelUpdateAction::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    obj->insert("id", QJsonValue(id));
    toJsonValue(QString("action"), action, obj, QString("QString"));
    toJsonValue(QString("subject_data"), subject_data, obj, QString("QString"));
    toJsonValue(QString("subject_type"), subject_type, obj, QString("QString"));

    return obj;
}

qint32
ModelUpdateAction::getId() {
    return id;
}
void
ModelUpdateAction::setId(qint32 id) {
    this->id = id;
}

QString*
ModelUpdateAction::getAction() {
    return action;
}
void
ModelUpdateAction::setAction(QString* action) {
    this->action = action;
}

QString*
ModelUpdateAction::getSubjectData() {
    return subject_data;
}
void
ModelUpdateAction::setSubjectData(QString* subject_data) {
    this->subject_data = subject_data;
}

QString*
ModelUpdateAction::getSubjectType() {
    return subject_type;
}
void
ModelUpdateAction::setSubjectType(QString* subject_type) {
    this->subject_type = subject_type;
}


}

