/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ModelMachineLogin.h
 * 
 * 
 */

#ifndef ModelMachineLogin_H_
#define ModelMachineLogin_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"

namespace api {

class ModelMachineLogin: public SWGObject {
public:
    ModelMachineLogin();
    ModelMachineLogin(QString* json);
    virtual ~ModelMachineLogin();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    ModelMachineLogin* fromJson(QString &jsonString);

    QString* getRfidUser();
    void setRfidUser(QString* rfid_user);

    QString* getPinCode();
    void setPinCode(QString* pin_code);

    QString* getRfidVehicle();
    void setRfidVehicle(QString* rfid_vehicle);


private:
    QString* rfid_user;
    QString* pin_code;
    QString* rfid_vehicle;
};

}

#endif /* ModelMachineLogin_H_ */
