/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ModelReceiptDetail.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace api {

ModelReceiptDetail::ModelReceiptDetail(QString* json) {
    init();
    this->fromJson(*json);
}

ModelReceiptDetail::ModelReceiptDetail() {
    init();
}

ModelReceiptDetail::~ModelReceiptDetail() {
    this->cleanup();
}

void
ModelReceiptDetail::init() {
    transactions = new QList<ModelReceiptTransaction*>();
    summary = new QList<ModelReceiptSummary*>();
}

void
ModelReceiptDetail::cleanup() {
    if(transactions != nullptr) {
        QList<ModelReceiptTransaction*>* arr = transactions;
        foreach(ModelReceiptTransaction* o, *arr) {
            delete o;
        }
        delete transactions;
    }
    if(summary != nullptr) {
        QList<ModelReceiptSummary*>* arr = summary;
        foreach(ModelReceiptSummary* o, *arr) {
            delete o;
        }
        delete summary;
    }
}

ModelReceiptDetail*
ModelReceiptDetail::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ModelReceiptDetail::fromJsonObject(QJsonObject &pJson) {
    ::api::setValue(&transactions, pJson["transactions"], "QList", "ModelReceiptTransaction");
    ::api::setValue(&summary, pJson["summary"], "QList", "ModelReceiptSummary");
}

QString
ModelReceiptDetail::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
ModelReceiptDetail::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    QJsonArray transactionsJsonArray;
    toJsonArray((QList<void*>*)transactions, &transactionsJsonArray, "transactions", "ModelReceiptTransaction");
    obj->insert("transactions", transactionsJsonArray);
    QJsonArray summaryJsonArray;
    toJsonArray((QList<void*>*)summary, &summaryJsonArray, "summary", "ModelReceiptSummary");
    obj->insert("summary", summaryJsonArray);

    return obj;
}

QList<ModelReceiptTransaction*>*
ModelReceiptDetail::getTransactions() {
    return transactions;
}
void
ModelReceiptDetail::setTransactions(QList<ModelReceiptTransaction*>* transactions) {
    this->transactions = transactions;
}

QList<ModelReceiptSummary*>*
ModelReceiptDetail::getSummary() {
    return summary;
}
void
ModelReceiptDetail::setSummary(QList<ModelReceiptSummary*>* summary) {
    this->summary = summary;
}


}

