/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ModelRevenueChart.h
 * 
 * 
 */

#ifndef ModelRevenueChart_H_
#define ModelRevenueChart_H_

#include <QJsonObject>


#include <QDateTime>
#include <QString>

#include "SWGObject.h"

namespace api {

class ModelRevenueChart: public SWGObject {
public:
    ModelRevenueChart();
    ModelRevenueChart(QString* json);
    virtual ~ModelRevenueChart();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    ModelRevenueChart* fromJson(QString &jsonString);

    QString* getTitleChart();
    void setTitleChart(QString* title_chart);

    qint64 getShiftId();
    void setShiftId(qint64 shift_id);

    float getSubTotal();
    void setSubTotal(float sub_total);

    float getTotal();
    void setTotal(float total);

    QDateTime* getDatetime();
    void setDatetime(QDateTime* datetime);


private:
    QString* title_chart;
    qint64 shift_id;
    float sub_total;
    float total;
    QDateTime* datetime;
};

}

#endif /* ModelRevenueChart_H_ */
