/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#include "SWGAdminPermissionsApi.h"
#include "SWGHelpers.h"
#include "SWGModelFactory.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace api {

SWGAdminPermissionsApi::SWGAdminPermissionsApi() {}

SWGAdminPermissionsApi::~SWGAdminPermissionsApi() {}

SWGAdminPermissionsApi::SWGAdminPermissionsApi(QString host, QString basePath) {
    this->host = host;
    this->basePath = basePath;
}

void
SWGAdminPermissionsApi::createPermission(ModelPermissionForm body) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/admin/permissions");



    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "POST");


    QString output = body.asJson();
    input.request_body.append(output);
    


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGAdminPermissionsApi::createPermissionCallback);

    worker->execute(&input);
}

void
SWGAdminPermissionsApi::createPermissionCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }


    QString json(worker->response);
    ModelPermission* output = static_cast<ModelPermission*>(create(json, QString("ModelPermission")));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit createPermissionSignal(output);
    } else {
        emit createPermissionSignalE(output, error_type, error_str);
        emit createPermissionSignalEFull(worker, error_type, error_str);
    }
}

void
SWGAdminPermissionsApi::deletePermission(qint64 permission_id) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/admin/permissions/{permissionId}");

    QString permission_idPathParam("{"); permission_idPathParam.append("permissionId").append("}");
    fullPath.replace(permission_idPathParam, stringValue(permission_id));


    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "DELETE");





    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGAdminPermissionsApi::deletePermissionCallback);

    worker->execute(&input);
}

void
SWGAdminPermissionsApi::deletePermissionCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit deletePermissionSignal();
    } else {
        emit deletePermissionSignalE(error_type, error_str);
        emit deletePermissionSignalEFull(worker, error_type, error_str);
    }
}

void
SWGAdminPermissionsApi::getPermissionById(qint64 permission_id) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/admin/permissions/{permissionId}");

    QString permission_idPathParam("{"); permission_idPathParam.append("permissionId").append("}");
    fullPath.replace(permission_idPathParam, stringValue(permission_id));


    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "GET");





    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGAdminPermissionsApi::getPermissionByIdCallback);

    worker->execute(&input);
}

void
SWGAdminPermissionsApi::getPermissionByIdCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }


    QString json(worker->response);
    ModelPermission* output = static_cast<ModelPermission*>(create(json, QString("ModelPermission")));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit getPermissionByIdSignal(output);
    } else {
        emit getPermissionByIdSignalE(output, error_type, error_str);
        emit getPermissionByIdSignalEFull(worker, error_type, error_str);
    }
}

void
SWGAdminPermissionsApi::listPermissions(qint32 page, qint32 limit) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/admin/permissions");


    if (fullPath.indexOf("?") > 0) 
      fullPath.append("&");
    else 
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("page"))
        .append("=")
        .append(QUrl::toPercentEncoding(stringValue(page)));

    if (fullPath.indexOf("?") > 0) 
      fullPath.append("&");
    else 
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("limit"))
        .append("=")
        .append(QUrl::toPercentEncoding(stringValue(limit)));


    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "GET");





    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGAdminPermissionsApi::listPermissionsCallback);

    worker->execute(&input);
}

void
SWGAdminPermissionsApi::listPermissionsCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    QList<ModelPermission*>* output = new QList<ModelPermission*>();
    QString json(worker->response);
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonArray jsonArray = doc.array();

    foreach(QJsonValue obj, jsonArray) {
        ModelPermission* o = new ModelPermission();
        QJsonObject jv = obj.toObject();
        QJsonObject * ptr = (QJsonObject*)&jv;
        o->fromJsonObject(*ptr);
        output->append(o);
    }

    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit listPermissionsSignal(output);
    } else {
        emit listPermissionsSignalE(output, error_type, error_str);
        emit listPermissionsSignalEFull(worker, error_type, error_str);
    }
}

void
SWGAdminPermissionsApi::updatePermission(ModelPermissionForm body) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/admin/permissions");



    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "PATCH");


    QString output = body.asJson();
    input.request_body.append(output);
    


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGAdminPermissionsApi::updatePermissionCallback);

    worker->execute(&input);
}

void
SWGAdminPermissionsApi::updatePermissionCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }


    QString json(worker->response);
    ModelPermission* output = static_cast<ModelPermission*>(create(json, QString("ModelPermission")));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit updatePermissionSignal(output);
    } else {
        emit updatePermissionSignalE(output, error_type, error_str);
        emit updatePermissionSignalEFull(worker, error_type, error_str);
    }
}


}
