/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#ifndef _SWG_SWGMachineTicketAllocatesApi_H_
#define _SWG_SWGMachineTicketAllocatesApi_H_

#include "SWGHttpRequest.h"

#include "ModelTicketAllocate.h"
#include <QList>

#include <QObject>

namespace api {

class SWGMachineTicketAllocatesApi: public QObject {
    Q_OBJECT

public:
    SWGMachineTicketAllocatesApi();
    SWGMachineTicketAllocatesApi(QString host, QString basePath);
    ~SWGMachineTicketAllocatesApi();

    QString host;
    QString basePath;
    QMap<QString, QString> defaultHeaders;

    void machineTicketAllocates(QList<qint32>* body);
    
private:
    void machineTicketAllocatesCallback (HttpRequestWorker * worker);
    
signals:
    void machineTicketAllocatesSignal(QList<ModelTicketAllocate*>* summary);
    
    void machineTicketAllocatesSignalE(QList<ModelTicketAllocate*>* summary, QNetworkReply::NetworkError error_type, QString& error_str);
    
    void machineTicketAllocatesSignalEFull(HttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    
};

}
#endif
