/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#ifndef _SWG_SWGManagerCompaniesApi_H_
#define _SWG_SWGManagerCompaniesApi_H_

#include "SWGHttpRequest.h"

#include "ModelCompany.h"
#include "ModelCompanyUpdate.h"

#include <QObject>

namespace api {

class SWGManagerCompaniesApi: public QObject {
    Q_OBJECT

public:
    SWGManagerCompaniesApi();
    SWGManagerCompaniesApi(QString host, QString basePath);
    ~SWGManagerCompaniesApi();

    QString host;
    QString basePath;
    QMap<QString, QString> defaultHeaders;

    void managerGetCompany();
    void managerUpdateCompany(ModelCompanyUpdate body);
    
private:
    void managerGetCompanyCallback (HttpRequestWorker * worker);
    void managerUpdateCompanyCallback (HttpRequestWorker * worker);
    
signals:
    void managerGetCompanySignal(ModelCompany* summary);
    void managerUpdateCompanySignal(ModelCompany* summary);
    
    void managerGetCompanySignalE(ModelCompany* summary, QNetworkReply::NetworkError error_type, QString& error_str);
    void managerUpdateCompanySignalE(ModelCompany* summary, QNetworkReply::NetworkError error_type, QString& error_str);
    
    void managerGetCompanySignalEFull(HttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    void managerUpdateCompanySignalEFull(HttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    
};

}
#endif
