/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#include "SWGMachineUpdateApi.h"
#include "SWGHelpers.h"
#include "SWGModelFactory.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace api {

SWGMachineUpdateApi::SWGMachineUpdateApi() {}

SWGMachineUpdateApi::~SWGMachineUpdateApi() {}

SWGMachineUpdateApi::SWGMachineUpdateApi(QString host, QString basePath) {
    this->host = host;
    this->basePath = basePath;
}

void
SWGMachineUpdateApi::machineUpdateActivities(QList<ModelMachineActivity*>* body) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/machine/update/activities");



    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "POST");


    QJsonArray* bodyArray = new QJsonArray();
    toJsonArray((QList<void*>*)body, bodyArray, QString("body"), QString("SWGUser*"));

    QJsonDocument doc(*bodyArray);
    QByteArray bytes = doc.toJson();

    input.request_body.append(bytes);



    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGMachineUpdateApi::machineUpdateActivitiesCallback);

    worker->execute(&input);
}

void
SWGMachineUpdateApi::machineUpdateActivitiesCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }


    QString json(worker->response);
    ModelGenericResponse* output = static_cast<ModelGenericResponse*>(create(json, QString("ModelGenericResponse")));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit machineUpdateActivitiesSignal(output);
    } else {
        emit machineUpdateActivitiesSignalE(output, error_type, error_str);
        emit machineUpdateActivitiesSignalEFull(worker, error_type, error_str);
    }
}

void
SWGMachineUpdateApi::machineUpdateDatabase(qint32 from) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/machine/update/database");


    if (fullPath.indexOf("?") > 0) 
      fullPath.append("&");
    else 
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("from"))
        .append("=")
        .append(QUrl::toPercentEncoding(stringValue(from)));


    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "GET");





    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGMachineUpdateApi::machineUpdateDatabaseCallback);

    worker->execute(&input);
}

void
SWGMachineUpdateApi::machineUpdateDatabaseCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    QList<ModelUpdateAction*>* output = new QList<ModelUpdateAction*>();
    QString json(worker->response);
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonArray jsonArray = doc.array();

    foreach(QJsonValue obj, jsonArray) {
        ModelUpdateAction* o = new ModelUpdateAction();
        QJsonObject jv = obj.toObject();
        QJsonObject * ptr = (QJsonObject*)&jv;
        o->fromJsonObject(*ptr);
        output->append(o);
    }

    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit machineUpdateDatabaseSignal(output);
    } else {
        emit machineUpdateDatabaseSignalE(output, error_type, error_str);
        emit machineUpdateDatabaseSignalEFull(worker, error_type, error_str);
    }
}

void
SWGMachineUpdateApi::machineUpdateFirmware(QString* version) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/machine/update/firmware");


    if (fullPath.indexOf("?") > 0) 
      fullPath.append("&");
    else 
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("version"))
        .append("=")
        .append(QUrl::toPercentEncoding(stringValue(version)));


    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "GET");





    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGMachineUpdateApi::machineUpdateFirmwareCallback);

    worker->execute(&input);
}

void
SWGMachineUpdateApi::machineUpdateFirmwareCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }


    QString json(worker->response);
    ModelFirmware* output = static_cast<ModelFirmware*>(create(json, QString("ModelFirmware")));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit machineUpdateFirmwareSignal(output);
    } else {
        emit machineUpdateFirmwareSignalE(output, error_type, error_str);
        emit machineUpdateFirmwareSignalEFull(worker, error_type, error_str);
    }
}

void
SWGMachineUpdateApi::machineUpdatePing() {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/machine/update/ping");



    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "GET");





    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGMachineUpdateApi::machineUpdatePingCallback);

    worker->execute(&input);
}

void
SWGMachineUpdateApi::machineUpdatePingCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }


    QString json(worker->response);
    ModelPing* output = static_cast<ModelPing*>(create(json, QString("ModelPing")));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit machineUpdatePingSignal(output);
    } else {
        emit machineUpdatePingSignalE(output, error_type, error_str);
        emit machineUpdatePingSignalEFull(worker, error_type, error_str);
    }
}

void
SWGMachineUpdateApi::machineUpdatePostion(QList<ModelGPSRecord*>* body) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/machine/update/postion");



    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "POST");


    QJsonArray* bodyArray = new QJsonArray();
    toJsonArray((QList<void*>*)body, bodyArray, QString("body"), QString("SWGUser*"));

    QJsonDocument doc(*bodyArray);
    QByteArray bytes = doc.toJson();

    input.request_body.append(bytes);



    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGMachineUpdateApi::machineUpdatePostionCallback);

    worker->execute(&input);
}

void
SWGMachineUpdateApi::machineUpdatePostionCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }


    QString json(worker->response);
    ModelGenericResponse* output = static_cast<ModelGenericResponse*>(create(json, QString("ModelGenericResponse")));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit machineUpdatePostionSignal(output);
    } else {
        emit machineUpdatePostionSignalE(output, error_type, error_str);
        emit machineUpdatePostionSignalEFull(worker, error_type, error_str);
    }
}


}
