/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#include "SWGManagerPrepaidcardsApi.h"
#include "SWGHelpers.h"
#include "SWGModelFactory.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace api {

SWGManagerPrepaidcardsApi::SWGManagerPrepaidcardsApi() {}

SWGManagerPrepaidcardsApi::~SWGManagerPrepaidcardsApi() {}

SWGManagerPrepaidcardsApi::SWGManagerPrepaidcardsApi(QString host, QString basePath) {
    this->host = host;
    this->basePath = basePath;
}

void
SWGManagerPrepaidcardsApi::managerCreatePrepaidcard(ModelPrepaidCardForm body) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/manager/prepaidcards");



    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "POST");


    QString output = body.asJson();
    input.request_body.append(output);
    


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGManagerPrepaidcardsApi::managerCreatePrepaidcardCallback);

    worker->execute(&input);
}

void
SWGManagerPrepaidcardsApi::managerCreatePrepaidcardCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }


    QString json(worker->response);
    ModelPrepaidCard* output = static_cast<ModelPrepaidCard*>(create(json, QString("ModelPrepaidCard")));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit managerCreatePrepaidcardSignal(output);
    } else {
        emit managerCreatePrepaidcardSignalE(output, error_type, error_str);
        emit managerCreatePrepaidcardSignalEFull(worker, error_type, error_str);
    }
}

void
SWGManagerPrepaidcardsApi::managerDeletePrepaidcard(qint64 prepaidcard_id) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/manager/prepaidcards/{prepaidcardId}");

    QString prepaidcard_idPathParam("{"); prepaidcard_idPathParam.append("prepaidcardId").append("}");
    fullPath.replace(prepaidcard_idPathParam, stringValue(prepaidcard_id));


    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "DELETE");





    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGManagerPrepaidcardsApi::managerDeletePrepaidcardCallback);

    worker->execute(&input);
}

void
SWGManagerPrepaidcardsApi::managerDeletePrepaidcardCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit managerDeletePrepaidcardSignal();
    } else {
        emit managerDeletePrepaidcardSignalE(error_type, error_str);
        emit managerDeletePrepaidcardSignalEFull(worker, error_type, error_str);
    }
}

void
SWGManagerPrepaidcardsApi::managerGetPrepaidcardsById(qint64 prepaidcard_id) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/manager/prepaidcards/{prepaidcardId}");

    QString prepaidcard_idPathParam("{"); prepaidcard_idPathParam.append("prepaidcardId").append("}");
    fullPath.replace(prepaidcard_idPathParam, stringValue(prepaidcard_id));


    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "GET");





    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGManagerPrepaidcardsApi::managerGetPrepaidcardsByIdCallback);

    worker->execute(&input);
}

void
SWGManagerPrepaidcardsApi::managerGetPrepaidcardsByIdCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }


    QString json(worker->response);
    ModelPrepaidCard* output = static_cast<ModelPrepaidCard*>(create(json, QString("ModelPrepaidCard")));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit managerGetPrepaidcardsByIdSignal(output);
    } else {
        emit managerGetPrepaidcardsByIdSignalE(output, error_type, error_str);
        emit managerGetPrepaidcardsByIdSignalEFull(worker, error_type, error_str);
    }
}

void
SWGManagerPrepaidcardsApi::managerUpdatePrepaidcard(ModelPrepaidCardForm body) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/manager/prepaidcards");



    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "PATCH");


    QString output = body.asJson();
    input.request_body.append(output);
    


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGManagerPrepaidcardsApi::managerUpdatePrepaidcardCallback);

    worker->execute(&input);
}

void
SWGManagerPrepaidcardsApi::managerUpdatePrepaidcardCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }


    QString json(worker->response);
    ModelPrepaidCard* output = static_cast<ModelPrepaidCard*>(create(json, QString("ModelPrepaidCard")));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit managerUpdatePrepaidcardSignal(output);
    } else {
        emit managerUpdatePrepaidcardSignalE(output, error_type, error_str);
        emit managerUpdatePrepaidcardSignalEFull(worker, error_type, error_str);
    }
}

void
SWGManagerPrepaidcardsApi::managerlistPrepaidcards() {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/manager/prepaidcards");



    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "GET");





    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGManagerPrepaidcardsApi::managerlistPrepaidcardsCallback);

    worker->execute(&input);
}

void
SWGManagerPrepaidcardsApi::managerlistPrepaidcardsCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    QList<ModelPrepaidCard*>* output = new QList<ModelPrepaidCard*>();
    QString json(worker->response);
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonArray jsonArray = doc.array();

    foreach(QJsonValue obj, jsonArray) {
        ModelPrepaidCard* o = new ModelPrepaidCard();
        QJsonObject jv = obj.toObject();
        QJsonObject * ptr = (QJsonObject*)&jv;
        o->fromJsonObject(*ptr);
        output->append(o);
    }

    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit managerlistPrepaidcardsSignal(output);
    } else {
        emit managerlistPrepaidcardsSignalE(output, error_type, error_str);
        emit managerlistPrepaidcardsSignalEFull(worker, error_type, error_str);
    }
}


}
