/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#include "SWGManagerShiftsApi.h"
#include "SWGHelpers.h"
#include "SWGModelFactory.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace api {

SWGManagerShiftsApi::SWGManagerShiftsApi() {}

SWGManagerShiftsApi::~SWGManagerShiftsApi() {}

SWGManagerShiftsApi::SWGManagerShiftsApi(QString host, QString basePath) {
    this->host = host;
    this->basePath = basePath;
}

void
SWGManagerShiftsApi::managerShiftsUpdateCollected(ModelCollected body) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/manager/shifts/collected");



    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "POST");


    QString output = body.asJson();
    input.request_body.append(output);
    


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGManagerShiftsApi::managerShiftsUpdateCollectedCallback);

    worker->execute(&input);
}

void
SWGManagerShiftsApi::managerShiftsUpdateCollectedCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }


    QString json(worker->response);
    QString* output = static_cast<QString*>(create(json, QString("QString")));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit managerShiftsUpdateCollectedSignal(output);
    } else {
        emit managerShiftsUpdateCollectedSignalE(output, error_type, error_str);
        emit managerShiftsUpdateCollectedSignalEFull(worker, error_type, error_str);
    }
}


}
