/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#include "SWGManagerDevicesApi.h"
#include "SWGHelpers.h"
#include "SWGModelFactory.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace api {

SWGManagerDevicesApi::SWGManagerDevicesApi() {}

SWGManagerDevicesApi::~SWGManagerDevicesApi() {}

SWGManagerDevicesApi::SWGManagerDevicesApi(QString host, QString basePath) {
    this->host = host;
    this->basePath = basePath;
}

void
SWGManagerDevicesApi::managerDeviceGetRevenueById(qint64 device_id) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/manager/devices/{deviceId}/revenue");

    QString device_idPathParam("{"); device_idPathParam.append("deviceId").append("}");
    fullPath.replace(device_idPathParam, stringValue(device_id));


    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "GET");





    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGManagerDevicesApi::managerDeviceGetRevenueByIdCallback);

    worker->execute(&input);
}

void
SWGManagerDevicesApi::managerDeviceGetRevenueByIdCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    QList<ModelRevenueChart*>* output = new QList<ModelRevenueChart*>();
    QString json(worker->response);
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonArray jsonArray = doc.array();

    foreach(QJsonValue obj, jsonArray) {
        ModelRevenueChart* o = new ModelRevenueChart();
        QJsonObject jv = obj.toObject();
        QJsonObject * ptr = (QJsonObject*)&jv;
        o->fromJsonObject(*ptr);
        output->append(o);
    }

    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit managerDeviceGetRevenueByIdSignal(output);
    } else {
        emit managerDeviceGetRevenueByIdSignalE(output, error_type, error_str);
        emit managerDeviceGetRevenueByIdSignalEFull(worker, error_type, error_str);
    }
}

void
SWGManagerDevicesApi::managerGetDeviceById(qint64 device_id) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/manager/devices/{deviceId}");

    QString device_idPathParam("{"); device_idPathParam.append("deviceId").append("}");
    fullPath.replace(device_idPathParam, stringValue(device_id));


    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "GET");





    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGManagerDevicesApi::managerGetDeviceByIdCallback);

    worker->execute(&input);
}

void
SWGManagerDevicesApi::managerGetDeviceByIdCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }


    QString json(worker->response);
    ModelManagerDevice* output = static_cast<ModelManagerDevice*>(create(json, QString("ModelManagerDevice")));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit managerGetDeviceByIdSignal(output);
    } else {
        emit managerGetDeviceByIdSignalE(output, error_type, error_str);
        emit managerGetDeviceByIdSignalEFull(worker, error_type, error_str);
    }
}

void
SWGManagerDevicesApi::managerListDevices(qint32 page, qint32 limit) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/manager/devices");


    if (fullPath.indexOf("?") > 0) 
      fullPath.append("&");
    else 
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("page"))
        .append("=")
        .append(QUrl::toPercentEncoding(stringValue(page)));

    if (fullPath.indexOf("?") > 0) 
      fullPath.append("&");
    else 
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("limit"))
        .append("=")
        .append(QUrl::toPercentEncoding(stringValue(limit)));


    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "GET");





    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGManagerDevicesApi::managerListDevicesCallback);

    worker->execute(&input);
}

void
SWGManagerDevicesApi::managerListDevicesCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    QList<ModelManagerDevice*>* output = new QList<ModelManagerDevice*>();
    QString json(worker->response);
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonArray jsonArray = doc.array();

    foreach(QJsonValue obj, jsonArray) {
        ModelManagerDevice* o = new ModelManagerDevice();
        QJsonObject jv = obj.toObject();
        QJsonObject * ptr = (QJsonObject*)&jv;
        o->fromJsonObject(*ptr);
        output->append(o);
    }

    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit managerListDevicesSignal(output);
    } else {
        emit managerListDevicesSignalE(output, error_type, error_str);
        emit managerListDevicesSignalEFull(worker, error_type, error_str);
    }
}


}
