/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#ifndef _SWG_SWGMobilePrepaidcardsApi_H_
#define _SWG_SWGMobilePrepaidcardsApi_H_

#include "SWGHttpRequest.h"

#include "ModelPrepaidCard.h"
#include <QString>

#include <QObject>

namespace api {

class SWGMobilePrepaidcardsApi: public QObject {
    Q_OBJECT

public:
    SWGMobilePrepaidcardsApi();
    SWGMobilePrepaidcardsApi(QString host, QString basePath);
    ~SWGMobilePrepaidcardsApi();

    QString host;
    QString basePath;
    QMap<QString, QString> defaultHeaders;

    void mobileGetPrepaidcardByBarcode(QString* barcode);
    
private:
    void mobileGetPrepaidcardByBarcodeCallback (HttpRequestWorker * worker);
    
signals:
    void mobileGetPrepaidcardByBarcodeSignal(ModelPrepaidCard* summary);
    
    void mobileGetPrepaidcardByBarcodeSignalE(ModelPrepaidCard* summary, QNetworkReply::NetworkError error_type, QString& error_str);
    
    void mobileGetPrepaidcardByBarcodeSignalEFull(HttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    
};

}
#endif
