/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#include "SWGMachineShiftsApi.h"
#include "SWGHelpers.h"
#include "SWGModelFactory.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace api {

SWGMachineShiftsApi::SWGMachineShiftsApi() {}

SWGMachineShiftsApi::~SWGMachineShiftsApi() {}

SWGMachineShiftsApi::SWGMachineShiftsApi(QString host, QString basePath) {
    this->host = host;
    this->basePath = basePath;
}

void
SWGMachineShiftsApi::machineLogin(ModelMachineLogin body) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/machine/shifts/login");



    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "POST");


    QString output = body.asJson();
    input.request_body.append(output);
    


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGMachineShiftsApi::machineLoginCallback);

    worker->execute(&input);
}

void
SWGMachineShiftsApi::machineLoginCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }


    QString json(worker->response);
    ModelMachineLoginView* output = static_cast<ModelMachineLoginView*>(create(json, QString("ModelMachineLoginView")));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit machineLoginSignal(output);
    } else {
        emit machineLoginSignalE(output, error_type, error_str);
        emit machineLoginSignalEFull(worker, error_type, error_str);
    }
}

void
SWGMachineShiftsApi::machineLogout() {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/machine/shifts/logout");



    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "POST");





    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGMachineShiftsApi::machineLogoutCallback);

    worker->execute(&input);
}

void
SWGMachineShiftsApi::machineLogoutCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }


    QString json(worker->response);
    ModelGenericResponse* output = static_cast<ModelGenericResponse*>(create(json, QString("ModelGenericResponse")));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit machineLogoutSignal(output);
    } else {
        emit machineLogoutSignalE(output, error_type, error_str);
        emit machineLogoutSignalEFull(worker, error_type, error_str);
    }
}

void
SWGMachineShiftsApi::machineUpdateRfidVehicle(ModelMachineLogin body) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/machine/shifts/updateRfidVehicle");



    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "POST");


    QString output = body.asJson();
    input.request_body.append(output);
    


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGMachineShiftsApi::machineUpdateRfidVehicleCallback);

    worker->execute(&input);
}

void
SWGMachineShiftsApi::machineUpdateRfidVehicleCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }


    QString json(worker->response);
    ModelMachineLoginView* output = static_cast<ModelMachineLoginView*>(create(json, QString("ModelMachineLoginView")));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit machineUpdateRfidVehicleSignal(output);
    } else {
        emit machineUpdateRfidVehicleSignalE(output, error_type, error_str);
        emit machineUpdateRfidVehicleSignalEFull(worker, error_type, error_str);
    }
}


}
