/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#ifndef _SWG_SWGManagerBusStationsApi_H_
#define _SWG_SWGManagerBusStationsApi_H_

#include "SWGHttpRequest.h"

#include "ModelBusStation.h"

#include <QObject>

namespace api {

class SWGManagerBusStationsApi: public QObject {
    Q_OBJECT

public:
    SWGManagerBusStationsApi();
    SWGManagerBusStationsApi(QString host, QString basePath);
    ~SWGManagerBusStationsApi();

    QString host;
    QString basePath;
    QMap<QString, QString> defaultHeaders;

    void managerlistBusStations(qint32 page, qint32 limit);
    
private:
    void managerlistBusStationsCallback (HttpRequestWorker * worker);
    
signals:
    void managerlistBusStationsSignal(QList<ModelBusStation*>* summary);
    
    void managerlistBusStationsSignalE(QList<ModelBusStation*>* summary, QNetworkReply::NetworkError error_type, QString& error_str);
    
    void managerlistBusStationsSignalEFull(HttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    
};

}
#endif
