/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#ifndef _SWG_SWGManagerShiftsApi_H_
#define _SWG_SWGManagerShiftsApi_H_

#include "SWGHttpRequest.h"

#include "ModelCollected.h"
#include <QString>

#include <QObject>

namespace api {

class SWGManagerShiftsApi: public QObject {
    Q_OBJECT

public:
    SWGManagerShiftsApi();
    SWGManagerShiftsApi(QString host, QString basePath);
    ~SWGManagerShiftsApi();

    QString host;
    QString basePath;
    QMap<QString, QString> defaultHeaders;

    void managerShiftsUpdateCollected(ModelCollected body);
    
private:
    void managerShiftsUpdateCollectedCallback (HttpRequestWorker * worker);
    
signals:
    void managerShiftsUpdateCollectedSignal(QString* summary);
    
    void managerShiftsUpdateCollectedSignalE(QString* summary, QNetworkReply::NetworkError error_type, QString& error_str);
    
    void managerShiftsUpdateCollectedSignalEFull(HttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    
};

}
#endif
