/**
 * SMARTBUS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#include "SWGManagerVehiclesApi.h"
#include "SWGHelpers.h"
#include "SWGModelFactory.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace api {

SWGManagerVehiclesApi::SWGManagerVehiclesApi() {}

SWGManagerVehiclesApi::~SWGManagerVehiclesApi() {}

SWGManagerVehiclesApi::SWGManagerVehiclesApi(QString host, QString basePath) {
    this->host = host;
    this->basePath = basePath;
}

void
SWGManagerVehiclesApi::managerCreateVehicle(ModelVehicleForm body) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/manager/vehicles");



    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "POST");


    QString output = body.asJson();
    input.request_body.append(output);
    


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGManagerVehiclesApi::managerCreateVehicleCallback);

    worker->execute(&input);
}

void
SWGManagerVehiclesApi::managerCreateVehicleCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }


    QString json(worker->response);
    ModelVehicle* output = static_cast<ModelVehicle*>(create(json, QString("ModelVehicle")));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit managerCreateVehicleSignal(output);
    } else {
        emit managerCreateVehicleSignalE(output, error_type, error_str);
        emit managerCreateVehicleSignalEFull(worker, error_type, error_str);
    }
}

void
SWGManagerVehiclesApi::managerDeleteVehicle(qint64 vehicle_id) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/manager/vehicles/{vehicleId}");

    QString vehicle_idPathParam("{"); vehicle_idPathParam.append("vehicleId").append("}");
    fullPath.replace(vehicle_idPathParam, stringValue(vehicle_id));


    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "DELETE");





    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGManagerVehiclesApi::managerDeleteVehicleCallback);

    worker->execute(&input);
}

void
SWGManagerVehiclesApi::managerDeleteVehicleCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit managerDeleteVehicleSignal();
    } else {
        emit managerDeleteVehicleSignalE(error_type, error_str);
        emit managerDeleteVehicleSignalEFull(worker, error_type, error_str);
    }
}

void
SWGManagerVehiclesApi::managerGetVehicleById(qint64 vehicle_id) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/manager/vehicles/{vehicleId}");

    QString vehicle_idPathParam("{"); vehicle_idPathParam.append("vehicleId").append("}");
    fullPath.replace(vehicle_idPathParam, stringValue(vehicle_id));


    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "GET");





    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGManagerVehiclesApi::managerGetVehicleByIdCallback);

    worker->execute(&input);
}

void
SWGManagerVehiclesApi::managerGetVehicleByIdCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }


    QString json(worker->response);
    ModelVehicle* output = static_cast<ModelVehicle*>(create(json, QString("ModelVehicle")));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit managerGetVehicleByIdSignal(output);
    } else {
        emit managerGetVehicleByIdSignalE(output, error_type, error_str);
        emit managerGetVehicleByIdSignalEFull(worker, error_type, error_str);
    }
}

void
SWGManagerVehiclesApi::managerUpdateVehicle(ModelVehicleForm body) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/manager/vehicles");



    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "PATCH");


    QString output = body.asJson();
    input.request_body.append(output);
    


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGManagerVehiclesApi::managerUpdateVehicleCallback);

    worker->execute(&input);
}

void
SWGManagerVehiclesApi::managerUpdateVehicleCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }


    QString json(worker->response);
    ModelVehicle* output = static_cast<ModelVehicle*>(create(json, QString("ModelVehicle")));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit managerUpdateVehicleSignal(output);
    } else {
        emit managerUpdateVehicleSignalE(output, error_type, error_str);
        emit managerUpdateVehicleSignalEFull(worker, error_type, error_str);
    }
}

void
SWGManagerVehiclesApi::managerVehicleAssignRoute(ModelVehicleForm body) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/manager/vehicles/assignRoute");



    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "POST");


    QString output = body.asJson();
    input.request_body.append(output);
    


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGManagerVehiclesApi::managerVehicleAssignRouteCallback);

    worker->execute(&input);
}

void
SWGManagerVehiclesApi::managerVehicleAssignRouteCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }


    QString json(worker->response);
    ModelVehicle* output = static_cast<ModelVehicle*>(create(json, QString("ModelVehicle")));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit managerVehicleAssignRouteSignal(output);
    } else {
        emit managerVehicleAssignRouteSignalE(output, error_type, error_str);
        emit managerVehicleAssignRouteSignalEFull(worker, error_type, error_str);
    }
}

void
SWGManagerVehiclesApi::managerlistVehicles(qint32 page, qint32 limit) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/manager/vehicles");


    if (fullPath.indexOf("?") > 0) 
      fullPath.append("&");
    else 
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("page"))
        .append("=")
        .append(QUrl::toPercentEncoding(stringValue(page)));

    if (fullPath.indexOf("?") > 0) 
      fullPath.append("&");
    else 
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("limit"))
        .append("=")
        .append(QUrl::toPercentEncoding(stringValue(limit)));


    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "GET");





    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGManagerVehiclesApi::managerlistVehiclesCallback);

    worker->execute(&input);
}

void
SWGManagerVehiclesApi::managerlistVehiclesCallback(HttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    QList<ModelVehicle*>* output = new QList<ModelVehicle*>();
    QString json(worker->response);
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonArray jsonArray = doc.array();

    foreach(QJsonValue obj, jsonArray) {
        ModelVehicle* o = new ModelVehicle();
        QJsonObject jv = obj.toObject();
        QJsonObject * ptr = (QJsonObject*)&jv;
        o->fromJsonObject(*ptr);
        output->append(o);
    }

    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit managerlistVehiclesSignal(output);
    } else {
        emit managerlistVehiclesSignalE(output, error_type, error_str);
        emit managerlistVehiclesSignalEFull(worker, error_type, error_str);
    }
}


}
